### ISSUE TITLE
A suggestion for the website when editing your bot.

### ISSUE THREAD

**Issue by Angrymedalists** [top-gg/issues#101]
#### Suggestion

Save the vimeo authorisation option so we don't have to tick it every time we edit the bot, nothing special but it would be a nice addition.

#### Applicable Links or Attachments

![What I'm talking about.](https://media.discordapp.net/attachments/264445053596991498/473634345157001226/unknown.png)

**Comment by Chewsterchew** [comment]
Yeah, only untick it when the video url changes, so you have to re-authorize on video change, not just every bot change.

**Comment by Xetera** [comment]
This is fixed in the upcoming edit page updates.
