### ISSUE TITLE
Only the first "music" tag is hyperlinked

### ISSUE THREAD

**Issue by fatchan** [top-gg/issues#102]
#### Expected Behavior

All tags that a bot has should be hyperlinked and lead to the page for that tag e.g. https://discordbots.org/tag/moderation

#### Observed Behavior

Only the music tag is clickable and only if it is the first tag.

#### Applicable Links or Attachments

[Image example](https://img.69420.me/99aKHY5v.gif)

#### Steps to Reproduce

1. Open Discordbots.org
2. Hover over the tags under a bot shown on the main page.
3. If it is not "music" and not the first tag shown, it cannot be clicked.

#### Web Browser and Version

Google Chrome Version 67.0.3396.99

#### Operating System and Version

Windows 7

#### Screen Resolution

1920x1080

**Comment by tonkku107** [comment]
Only the music tag being clickable is intended behavior.
The link only working on the first tag isn't
