### ISSUE TITLE
Stats for bots

### ISSUE THREAD

**Issue by Angrymedalists** [top-gg/issues#112]
#### Suggestion

Just a suggestion, it would be awesome to have stats for the bot e.g a graph for server count etc for the bots.

I was going to make one for my self but I thought it could be a nice addition for all the bot owners to keep track of their bot and how it's growing.

**Comment by Xetera** [comment]
This is going to be a part of our upcoming analytics update. 🎉

We're currently more interested in tracking traffic for bots and servers but is a feature that will be added later but server count is something that will be a part of that in future releases.
