### ISSUE TITLE
Implement the ability to add infinite owners

### ISSUE THREAD

**Issue by Nevvulo** [top-gg/issues#129]
#### Suggestion
I think that the primary owner of bots should have the option to add more than the default 3 owners to their bot, but only display the first 3 owners (in alphabetical order or by allowing the primary owner to choose) on the bot page.

I can hear it beyond the screen now;
### Blake, what about the abuse?!??!
I understand. The abuse would more than likely be through the roof, and here's why I'm also proposing another feature: **the ability to send _invites_ to developers regarding if they want to be added as an owner on that bot**. Invites would (ideally) appear on your user profile (private to you of course). This method is still susceptible to abuse, but this way it ensures that people can't just mass add you to your bot, and even if they tried, the only thing that would happen is the other user would receive an invite that could be declined or accepted. This system would work similar to GitHub invitations, or like Discord friend requests, where you need to know the user's ID before you can send them a request.

#### Applicable Links or Attachments
This is what a bot ownership request would look like: 
![image](https://absolute-legend.zblake.xyz/w9LwBQOU.png)
**EDIT**: I can see how a little "1" notification could be annoying to some, so this wouldn't be a necessary thing, just an idea. Bot ownership requests could remain silent in a tab in the user profiles.

Of course, it's a bit hard not knowing what the new user profile design will look like, but this is how I would envision the feature:
![image](https://absolute-legend.zblake.xyz/3h5vZUbj.png)

I hope you will consider this suggestion seriously, as this is a very real issue for a lot of people who own bots that have lots of people who contribute or develop on it. Thank you.

**Comment by tonkku107** [comment]
I have considered adding more spots, "invites", and likely splitting it into groups of owner (1), co-owners (2?) and developers (5?) with different permissions. However, I do not think an infinite amount is a good idea. Maybe the new system could allow us to be more flexible tho and grant people extra slots if they really need them.

**Comment by melmsie** [comment]
I have one co-owner and 6 developers. I approve :smile_cat:

**Comment by TheLearneer** [comment]
+1 to to the idea itself and yeah +1 to what Tonkku said as well.
Would be really awesome to have then splitted into groups of owners, co-owners and developers :smile:

**Comment by Andre601** [comment]
> ... and likely splitting it into groups of owner (1), co-owners (2?) and developers (5?) with different permissions.

What would be the "permissions"?

Like Owner has all rights, Co-Owner to update webhook and dev only update description?

**Comment by telkenes** [comment]
Tbh i like the idea just how bout certif bots... wont people just invite everyone so they can get the certif role?

**Comment by tonkku107** [comment]
Something will be done about that as well

**Comment by Oliyy** [comment]
9/10 for presentation

**Comment by WilsontheWolf** [comment]
what if we had a feature like a discord invite link where someone had to get the link to join (and then maybe confirm or give higher perms manually)

**Comment by Flam3rboy** [comment]
is this featured planned in the near future?

**Comment by Xetera** [comment]
We haven't spent too much talking about this internally yet but we want to address this issue with a teams system similar to discord's bot developer teams that let you add more than 3 (although I can't promise infinite) owners or developers to a bot. This feature is going to be important for managing permissions of bot developers for other upcoming features as well.

**Comment by Xetera** [comment]
This is now possible with the teams feature.
