### ISSUE TITLE
Add option to remove the medal.tv banner on the page

### ISSUE THREAD

**Issue by Andre601** [top-gg/issues#171]
#### Suggestion

I can understand, that you guys want to show and distribute the products you - or partners of you - made, but constantly having the banner on the site (specially with that annoying dark purple) makes it only annoying with the time.
When I go to the page, I want to edit my bot-page(s) and not want to see the banner on every single (sub-)page.
Also why did DonateBot had a removeable banner and medal.tv not?
So it would be much appreciated, when you could simply add an X with that you can close/remove the banner.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/11576465/46763427-1611c400-ccda-11e8-8b27-89e93fa2cbc4.png)

**Comment by Chewsterchew** [comment]
Especially since I don't even use Windows, and nobody cares about Medal, and the more you force it, the more we won't use it...

**Comment by Andre601** [comment]
Yeah.
I use windows, but I'm not interested in such stuff and for those who complain "You could just use an AdBlocker": No.
I'm a person that hates to use AdBlocker. And for one site is that also useless...
Also this is more a personal opinion, but I think that having no option, to remove that banner, is a cut into our freedom of choice (and could maybe be against law, but don't quote me on that)

**Comment by Chewsterchew** [comment]
AdBlock doesn't block the banner, it's not considered an ad. People can put whatever they want on their website, and if you agree to stay you agree you're fine with it. It's probably not against the law, why would it? But yeah, it's intrusive, messy, useless, and just kinda ruins the already pretty bad image of DBL as a whole.

**Comment by advaith1** [comment]
IIRC some adblockers let you hide specific elements on pages

**Comment by Chewsterchew** [comment]
Yeah, element blockers are usually a thing built into adblockers, but we shouldn't need an element to block in the first place

**Comment by Oliyy** [comment]
Thanks for expressing your concerns, we are hopefully planning to add a dismiss button for this banner.

**Comment by Chewsterchew** [comment]
This isn't fixed. We still can't close it on the server list.
