### ISSUE TITLE
Google Analytics improvements

### ISSUE THREAD

**Issue by Nathan-Webb** [top-gg/issues#229]
#### Suggestion

There needs to be a way for certified developers the ability to use google analytics for the site. Patreon does this for creators and it is as simple as adding another tag to the website code.
It would also be extremely useful for a way to track what page users came from in the search page / tag. This would give some more insight on what users search for and allow certified developers to make decisions based on where their users came from. 

#### Applicable Links or Attachments
GA Code Example
```
gtag('config', 'DBL-GA-CODE-HERE');
gtag('config', 'DEV-GA-CODE-HERE');
```

Link example

User would search "music bot radio", click on RadioBot123. And be sent to the bot page
The links for RadioBot123 would have `?search="music bot radio"` appended. 
Search link example: `https://discordbots.org/bot/124567890/?search=music_bot_radio`
Tag link example: `https://discordbots.org/bot/124567890/?tag=music`

**Comment by devakira** [comment]
Would 'official' Google analytics parameters such as utm_source and utm_medium be better for tracking?

**Comment by Nathan-Webb** [comment]
> Would 'official' Google analytics parameters such as utm_source and utm_medium be better for tracking?

Yea that would be better. I'm not too familiar with google analytics so i didn't know those would be better :P

**Comment by advaith1** [comment]
Certified developers can already use Google Analytics on bot pages, but I guess you're asking for more information about how users got to the page?

**Comment by Dr-Ari-Gami** [comment]
I think it would be helpful to regular bot developers, rather than certified ones, if there was a way you could provide a Google Analytics id as an option in the edit page, rather than having to be certified and use javascript.

**Comment by Xetera** [comment]
We have decided to not add custom google analytics. However, this feature will be covered by the custom analytics update that will be released soon which will include things like page view analytics, referrers, traffic by country, votes and more and will be available to all bot owners.
