### ISSUE TITLE
Endpoint to request the DBL webhook IP ranges and HMAC

### ISSUE THREAD

**Issue by Diniboy1123** [top-gg/issues#257]
#### Suggestion

Would you mind adding an endpoint, which could serve a simple text file that contains the current DBL webhook IP ranges? Would be amazing to be able to restrict the vote endpoint for example using a firewall for the DBL server only. 

Here is an example of how CloudFlare does it:

- [ipv4](https://www.cloudflare.com/ips-v4)
- [ipv6](https://www.cloudflare.com/ips-v6)

+ As another layer of "security", signing the request body via HMAC, where the key should be the auth header we set on the page would also be really awesome.

An example from Patreon:

> X-Patreon-Signature: [message signature]
> 
> where the message signature is the HEX digest of the message body HMAC signed (with MD5) using your webhook's secret viewable on the webhooks page. You can use this to verify us as the sender of the message.

Thank you

**Comment by Diniboy1123** [comment]
Any news on this one?

**Comment by Diniboy1123** [comment]
I would still like to see this implemented.

**Comment by Xetera** [comment]
This is currently low priority as there is already an existing way to verify webhooks. Security is of course important but we have plans on moving our infrastructure and I don't want to break people's firewalls

**Comment by Xetera** [comment]
The IP ranges are now accessible through https://docs.top.gg/resources/webhooks/#security. It's been a while since this issue was opened and I have not heard this request from other users since. If you're still using top.gg and would like to see this implemented, feel free to open another issue explaining your usecase 👍
