### ISSUE TITLE
"Create invite for you" not working

### ISSUE THREAD

**Issue by Luke-6723** [top-gg/issues#292]
#### Expected Behavior
Discord Server List will create an invite for you

#### Observed Behavior
![This](https://i.imgur.com/nONOWV3.png)

#### Applicable Links or Attachments

![Image 1](https://i.imgur.com/6WuhBo6.png)

#### Steps to Reproduce

1. Open Discordbots.org/servers/new
2. Have a similar layout to [Image 1](https://i.imgur.com/6WuhBo6.png)
3. Try to edit/add your server

#### Web Browser and Version

Google Chrome | 74.0.3729.131 (Official Build) (64-bit) (cohort: 74_131_Win)

#### Operating System and Version

Windows 10 1809

#### Screen Resolution

1920x1080

#### Additional Information/Comments

I have given it Create invite perms and admin perms.

**Comment by Luke-6723** [comment]
setting a permanent invite works fine. This only happens when trying to let the bot create an invite

**Comment by Xignotic84** [comment]
You need to make sure that the bot is in the server and has Create Invite permissions added.

**Comment by Luke-6723** [comment]
Just did a test with the #information channel being the top channel. When the channel is the first channel it works fine. But when the catagory is the first it stops working

**Comment by codeinteger6** [comment]
> Just did a test with the #information channel being the top channel. When the channel is the first channel it works fine. But when the catagory is the first it stops working

It doesn't work for me, even when the channel is the first one. And the bot has the Create Invite permission.

**Comment by Luke-6723** [comment]
Any reason this was close, has it been fixed?
