### ISSUE TITLE
Preview long description when adding a new bot

### ISSUE THREAD

**Issue by Fyko** [top-gg/issues#296]
I think it would be a great idea to add the **Preview** option when adding a new bot. This helps developers look at their long description when submitting new bot so they don't have to go about editing it after they submitted the application

Editing application:
![image](https://user-images.githubusercontent.com/45381083/58652218-ebf02f00-82c7-11e9-9199-ec2701f7f0c1.png)

Adding a new application:
![image](https://user-images.githubusercontent.com/45381083/58652237-f7435a80-82c7-11e9-9095-6f6fbc4d6a50.png)

**Comment by Luke-6723** [comment]
Yes

**Comment by Jacherr** [comment]
The site redesign does not appear to provide any way to preview the long description when either adding a new bot or editing an existing one. Is this feature still in consideration?

![image](https://user-images.githubusercontent.com/40544507/146681957-967bda34-1765-4792-bf50-3b33132d85be.png)

**Comment by bchurton** [comment]
You can preview a bot's description when submitting a bot, its right at the bottom next to "Submit"
![image](https://user-images.githubusercontent.com/66565286/146682017-6baecacc-e34c-444b-b345-cdd0d20e2a14.png)

**Comment by Jacherr** [comment]
Not sure how I managed to miss that.. In any case it would still be ideal to be able to preview changes to the long description when editing an existing bot.

**Comment by bchurton** [comment]
It's also possible on edit
![image](https://user-images.githubusercontent.com/66565286/146682098-24b8d13e-fdbd-47e1-976f-d2b2fe46a924.png)
