### ISSUE TITLE
jump_url to the Lucas' Starboard 

### ISSUE THREAD

**Issue by ssebastianoo** [top-gg/issues#306]
I think add the jump_url to the Luca' Starboard can be easier moving in to the messages.
Like [this](http://imgur.com/a/HFknndc)

**Comment by tonkku107** [comment]
There is currently no way to do this that looks acceptable in my opinion. All currently possible methods will look like crap. Can we get discord to add footer links (where message links also work instead of opening in the browser)?

**Comment by ssebastianoo** [comment]
Why not? For example (I use discord.py) you can use the
message.jump_url. Is this what you're asking for?

Il gio 18 lug 2019, 11:18 Tonkku <notifications@github.com> ha scritto:

**Comment by tonkku107** [comment]
That's not what I'm asking for

**Comment by Fyk0** [comment]
You can always use the embed's author URL field (highlighted in this image). It won't turn blue.

[`MessageEmbed#setAuthor`](https://discord.js.org/#/docs/main/master/class/MessageEmbed?scrollTo=setAuthor) (if Luca uses Djs)
![image](https://user-images.githubusercontent.com/45381083/63393989-d0526d00-c37a-11e9-866c-e47a0f8f06fd.png)

**Comment by tonkku107** [comment]
Setting a message link in the author field makes the link open in your browser instead of jumping

**Comment by NMW03** [comment]
Just create a blank field for that
