### ISSUE TITLE
[servers] html-tags improperly displaying when there's no server description

### ISSUE THREAD

**Issue by Fyko** [top-gg/issues#318]
Not sure if intentional but when viewing `servers/me` and there's a server that doesn't have a description, it displays as `<i>No description set.</i>`

![no-desc](https://user-images.githubusercontent.com/45381083/63393431-4f927180-c378-11e9-99d4-670d229019f8.png)

**Comment by Xignotic84** [comment]
This issue has been fixed in a recent update.
