### ISSUE TITLE
Role for server owners

### ISSUE THREAD

**Issue by AlexFlipnote** [top-gg/issues#338]
## Suggestion
Have a role for server owners in the official DBL server.

### Why exactly?
Before, DBL had a separate discord server for people who had their servers listed on the website. However, as time went on, it was decided to merge everything to DBL discord server. After such, I haven't seen any attempts to recover roles for server owners while the bot developers still can have roles as always. 

Why should us server owners who don't have a bot listed on the website be excluded from having a role on DBL discord?

-- AlexFlipnote

**Comment by Luke-6723** [comment]
wouldnt this be really hard to do without forcing the bot to make sure only the server owner gets the role. Some servers get admins to list the site. Which in turn would end up creating an easy way to bypass the Verification on dbl, since you could just list a server with infinite admins that get the role when they join dbl

**Comment by Luke-6723** [comment]
Possibly make there be a Minimum User Limit?

**Comment by AlexFlipnote** [comment]
It's easy to check owner of a guild and just hard-focus on only giving role to that person regardless if an admin of a specific server lists it. Or there could be a limit of only 1 role/server.

With guild member limit, I would suggest either 100, 250, 500 or 1,000 member limit. However that would kinda kill the meaning for small servers to attempt growing up with the website.

**Comment by tonkku107** [comment]
What about using the role to bypass server verification level?    
Servers are easy to create and there is no review process for them, so raiders could abuse that to skip verification level.

**Comment by AlexFlipnote** [comment]
Why not have a verification stage for server owners too then, to avoid abuse with server listing like bots have to go through then.

**Comment by tonkku107** [comment]
It's infeasible

**Comment by AlexFlipnote** [comment]
So what stops me from then (example) posting a NSFW server without anyone verifying at the beginning? Sure it might be banned later on, but I would then have already benefited from being listed for a while at the site. Wouldn't a verification stage at least help from getting servers that are pure troll, NSFW, Discord ToS breaking, etc?

![Preview](https://i.alexflipnote.dev/7o3gUFX.png)

**Comment by tonkku107** [comment]
Never said it wouldn't be useful
