### ISSUE TITLE
Adjust padding for long description

### ISSUE THREAD

**Issue by cheesits456** [top-gg/issues#341]
#### Suggestion

The long description, when viewed on mobile, is really narrow with an unnecessary amount of padding. In my opinion, the padding and/or margins should be reduced to make it look better.

#### Applicable Links or Attachments

![Screenshot_20191025-063514_Chrome](https://user-images.githubusercontent.com/35486894/67578622-b1b07f80-f6f7-11e9-9596-2745e1a1bdb7.jpg)

**Comment by braindigitalis** [comment]
I agree there is a lot of space, but were you aware you can specify your own stylesheets inline in the long description and adjust the width of this box as wide as you want? (i suggest ``padding: 0.25em`` and ``width: 90%`` and see how it looks).

**Comment by KevinNovak** [comment]
I came here to post this same issue but found yours. I agree, the description is being unnecessarily squished on mobile.

While @braindigitalis suggestion works, I feel this should be the default behavior. Thoughts?

**Comment by cheesits456** [comment]
It's incredibly simple to make the page apply a different width for that element depending on the window dimensions (which is usually a "close enough" representation of whether the browser is on a mobile device or not). Alternatively, something like [mobile-detect.js](https://github.com/hgoebl/mobile-detect.js) can be used if a more thorough/comprehensive test is desired. You can also fix it entirely in plain CSS using the `viewport` meta tag.

There are _so many_ different ways one could address this issue and fix it at the root, rather than telling people they have to manually add code themselves, just to make it look like what it should've in the first place

**Comment by tonkku107** [comment]
No need to get heated over the discussion. We, the developers, have not told you to use your own custom css to fix the issue.

**Comment by cheesits456** [comment]
I'm so sorry, I didn't realize that the original reply to this issue wasn't from a member of the dev team. I recently had a really terrible customer service experience with a large company, and I let that carry over to my interactions here. For that I apologize.

Going forward from here, this is theoretically quite an easy issue to resolve, and if there's anything I can do to help I'd be happy to.

**Comment by KevinNovak** [comment]
For those looking for a temporary fix, I added this to the bottom of my bot descriptions:
```html
<style>
    .page .container {
        padding-left: 5px;
        padding-right: 5px;
    }
    .longdescription {
        padding: 5px;
    }
</style>
```
