### ISSUE TITLE
Add Vote Widget Feature

### ISSUE THREAD

**Issue by minx28** [top-gg/issues#349]
There should be a feature on a bot's edit page with a box you can copy-paste containing code for an iframe that just has a vote button for the bot, would be very useful for people who want users who are visiting their bot's website to be able to vote quickly

**Comment by Xetera** [comment]
There are certain features (vote reminders but also more in the future) I think are important for voters to see when voting for bots. Also the majority of your monthly votes will probably come from your bot's existing userbase and not from random passers visiting the bot page.

This may be something that's open to reconsideration in the future but currently we don't have plans for this.
