### ISSUE TITLE
Add twitter tag

### ISSUE THREAD

**Issue by NMW03** [top-gg/issues#363]
#### Suggestion

I think you must be create twitter tag, because there is so many bots related with Twitter. Just type "twitter" to search: https://top.gg/search?q=twitter

**Comment by NMW03** [comment]
when™️

**Comment by Tenpi** [comment]
I would like this tag as well.

**Comment by zobos** [comment]
I'd find this useful

**Comment by Xetera** [comment]
I'll be closing this as we have a new user-defined tags system planned for sometime next month.
