### ISSUE TITLE
Trending New Bots goes 1, 2, 3, 5, 6, 7, 8

### ISSUE THREAD

**Issue by Luke-6723** [top-gg/issues#373]
This isnt a vital issue, but it should be known to the site admins

![image](https://user-images.githubusercontent.com/30714011/81481965-a18f6600-922b-11ea-9e66-6148483618a4.png)

**Comment by Luke-6723** [comment]
The number 4 feels left out my dudes

**Comment by LessH0pe** [comment]
> 
> 
> The number 4 feels left out my dudes
that poor 4

**Comment by velddev** [comment]
The numbers no longer display on trending new. Therefore it has been resolved?

**Comment by Luke-6723** [comment]
Fair fair
