### ISSUE TITLE
Add 'Last Oasis' to bot tags.

### ISSUE THREAD

**Issue by Jboonie** [top-gg/issues#383]
#### Suggestion

I think that the game **Last Oasis** should be an available tag for bots on top.gg

#### Applicable Links or Attachments

Here is a link to the game's store page on steam for reference on what 'Last Oasis' is:

[Steam Page: Last Oasis](https://store.steampowered.com/app/903950/Last_Oasis/)

**Comment by Xetera** [comment]
I've never heard of this game and there's not a single bot on topgg I can find that has this game in their description.
