### ISSUE TITLE
Add statistics for bots/servers 

### ISSUE THREAD

**Issue by TAG-Epic** [top-gg/issues#387]
#### Suggestion

 I think we should get a statistics dashboard so we can see statistics about our bot/server pages

### Why?
- Help people make their pages better

**Comment by slyfoxdiscord** [comment]
Maybe it could also show how many impressions the server/bot page has gotten.

**Comment by NMW03** [comment]
You can use https//dblstatistics.com

**Comment by Xetera** [comment]
This will be implemented in the upcoming analytics update this week.
