### ISSUE TITLE
Suggestion to add "Nitro" category on website

### ISSUE THREAD

**Issue by pkdev08** [top-gg/issues#388]
#### Suggestion

I think adding a "Nitro" tag for a category would be nice. My bot is one the first bots to have custom boost embeds whenever someone boosts ( even if they already have the Nitro Booster role ) and an optional for a log embed as well. Also, whenever a member stops boosting a server, that will be logged as well. Might be helpful for certain perks, etc for servers.

<img width="556" alt="boostLogs" src="https://user-images.githubusercontent.com/54294685/84077026-c00c8c80-a9a4-11ea-8003-8dbd44402e88.png">

![nitroBooster](https://user-images.githubusercontent.com/54294685/84077099-d4508980-a9a4-11ea-9882-9ebd6dcb1e12.png)

**Comment by Xetera** [comment]
There isn't any demand for something like this and it can already be searched for. I don't know why you felt the need to explain your bot's features in depth here, maybe next time try using https://top.gg/advertise and not GitHub issues.
