### ISSUE TITLE
feat(website): open source bot tag

### ISSUE THREAD

**Issue by SomeHumanCoder** [top-gg/issues#390]
#### Suggestion

I think we should introduce an open-source tag on the DBL Website because

- Open source enables anyone to improve code, fix bugs and security flaws
- Others could find it useful
- We can also compare open-source to something like science. If everyone would keep their methods secret, science would develop slower.

**Comment by Xetera** [comment]
I'll be closing this as we have a new user-defined tags system planned for sometime next month.
