### ISSUE TITLE
The edit profile button is not visible.

### ISSUE THREAD

**Issue by DuckMasterAl** [top-gg/issues#409]
#### Expected Behavior

The edit profile button is in black text or another color that makes it visible.

#### Observed Behavior

The edit profile button is on a white background with white text.

#### Applicable Links or Attachments

<img width="548" alt="Screen Shot 2020-08-08 at 7 07 40 PM" src="https://user-images.githubusercontent.com/43557963/89721383-db971200-d9aa-11ea-99b7-869529eb16d5.png">

#### Steps to Reproduce

1. Open top.gg
2. Login
3. Go to your profile
4. Do ctrl + a

#### Web Browser and Version

Chrome 84.0.4147.105 (64-bit)

#### Operating System and Version

MacOS Catalina 10.15.6 (19G73) - Macbook Pro 2017

#### Screen Resolution

2560 x 1600

**Comment by Xignotic84** [comment]
This issue should be fixed, if it's still an issue feel free to reopen this issue.
