### ISSUE TITLE
I am not able to invite bots

### ISSUE THREAD

**Issue by RiriDzns** [top-gg/issues#412]
I can't invite bots into my server or any of the server in which i am an Admin . After i click on the invite button on the discord bot list webpage , I get redirected to the android discord application , and , then I get a pop up that AuthOscope is not supportable with the app , it is supportable with the  browser , after i click on the 'Open in browser' button , it doesn't redirect me to the page ,  and then the appliction is closed and , discord bot list page is opened again , i am not able to do the recaptha and in invite bot , please help !! 
My discord username is : UҨΞ✗RiRi Dznsᴳᶠˣ
My tag is : #0642

**Comment by Xignotic84** [comment]
This is an issue with Discord's application not with top.gg
