### ISSUE TITLE
Progress Bar Public Queue System

### ISSUE THREAD

**Issue by dzlandis** [top-gg/issues#414]
#### Suggestion

It would be nice to have some sort of **progress bar** or **public queue system** to know what position your bot is in for getting accepted. I suggest a progress bar because it doesn't give the users too much information, or what it is currently, not enough information. I also think a progress bar would be good because it doesn't need to be 100% accurate. Thus, users would at least know a little bit about what the status is for acceptance on their bot.

The section could be above or right under where this area is:
![Screenshot from 2020-08-22 15-32-17](https://user-images.githubusercontent.com/49926644/90966887-b9ae8c80-e48c-11ea-88cd-a4f544a0c6e8.png)

An example of what the progress bar could look like:
![1_xNBXTvw5inpEqmExhuI0jg](https://user-images.githubusercontent.com/49926644/90966901-05f9cc80-e48d-11ea-93e4-5e94186141b3.png)

Please take this into consideration.

**Comment by Xetera** [comment]
Thanks for the idea, this was implemented in the last update.
