### ISSUE TITLE
Add bot invite page

### ISSUE THREAD

**Issue by MertBhey** [top-gg/issues#417]
#### Suggestion

I think you should add /invite to bot pages to top.gg
When people go to top.gg/bot/id/invite redirect to bot invite link

**Comment by Androz2091** [comment]
Good idea, I think this could be very very useful for support server invites. The day our invite expires, all we have to do is change the link on the edit page of our bot and it will be fine, whereas currently if an invite expires we have to change it everywhere in our bot (or finally buy a domain and redirect the users to the support server)

**Comment by Xignotic84** [comment]
This was recently implemented on top.gg.
