### ISSUE TITLE
Auctions application page can be resubmitted

### ISSUE THREAD

**Issue by jpbberry** [top-gg/issues#419]
#### Expected Behavior

Should redirect to auctions page if you've already applied and succeeded, or just stop the request for the application when submitting

#### Observed Behavior

Instead it lets me apply again

#### Steps to Reproduce

1. Be accepted to top.gg auctions
2. Go to the application page again top.gg/auctions/apply
3. Apply
4. It shouldn't go through as I've already applied and been accepted to auctions.

~~p.s please remove the test auction application I submitted to see if this worked :eyes:~~

**Comment by Xetera** [comment]
This suggestion was added
