### ISSUE TITLE
Remove trailing spaces from search.

### ISSUE THREAD

**Issue by Luke-6723** [top-gg/issues#420]
#### Expected Behavior

Typing `tag: Moderation ` into search bar and pressing search should take me to relative tag.

#### Observed Behavior

Takes me to https://top.gg/search?q=tag%3A%20Moderation%20

#### Applicable Links or Attachments

[](https://top.gg/search?q=tag%3A%20Moderation%20)

#### Steps to Reproduce

1. Open top.gg
2. Search `tag: Moderation ` (trailing space required)

#### Web Browser and Version

Google Chrome

#### Operating System and Version

Windows 10 64x

#### Screen Resolution

320×240

#### Additional Information/Comments

Remove trailing spaces from search

**Comment by CheweyZ** [comment]
![Result](https://cdn.discordapp.com/attachments/557980762675085333/754801440014336072/unknown.png)

**Comment by Xetera** [comment]
This issue has been fixed in this week's update👌 (which should be released by Wednesday)
