### ISSUE TITLE
Broken osu! server tag

### ISSUE THREAD

**Issue by Klarp** [top-gg/issues#421]
#### Expected Behavior

Searching the osu! tag on DSL will bring you to the osu! servers

#### Observed Behavior

Redirects you to the gaming tag instead.

#### Applicable Links or Attachments

[Link to osu! tag on actual tag](https://top.gg/servers/tag/osu!)
[Link that brings to osu! tag](https://top.gg/servers/tag/osu)

#### Steps to Reproduce

1. Open top.gg
2. Go to server list
3. Click on osu! tag
4. Be redirected to gaming

#### Web Browser and Version

Microsoft Edge Version 85.0.564.51 (Official build) (64-bit)

#### Operating System and Version

Windows 10 Home 1903

#### Screen Resolution

1920 x 1080

#### Additional Information/Comments

Though searching up osu instead of osu! in the link will bring you to the correct tag

**Comment by velddev** [comment]
Interesting. I think it is because of the `!` character. Not sure if it has any correlation with the uri spec.

**Comment by velddev** [comment]
Has been resolved a little while back 👍
