### ISSUE TITLE
Bugs in searching on the homepage

### ISSUE THREAD

**Issue by GerardSmit** [top-gg/issues#427]
#### Bugs
- [ ] When you type, pause and continue typing the results don't get updated. The second query doesn't get send and you see the old results.

	<details>
	<summary>Video</summary>
	<p>

     **Expected**
     ![image](https://user-images.githubusercontent.com/2109929/94854749-ad273780-042d-11eb-9bf9-5404580932d1.png)

     **Actual**     
     ![Video](https://user-images.githubusercontent.com/2109929/94854537-56b9f900-042d-11eb-9177-9f12ad9585fe.gif)

	</p>
	</details>

- [ ] Clicking a tag hides the results. Because the search box still has focus, you need to click somewhere else and then refocus the search box to show the results (typing won't show the results as well).

	<details>
	<summary>Video</summary>
	<img src="https://user-images.githubusercontent.com/2109929/94855181-64bc4980-042e-11eb-9177-8340e2a50c1c.gif" />
	</details>

- [ ] Sometimes clicking the results will just hide the results instead of going to the result.

	<details>
	<summary>Video</summary>
	<img src="https://user-images.githubusercontent.com/2109929/94855722-37bc6680-042f-11eb-9279-ebcdceb0f1aa.gif" />
	</details>

- [ ] When you already have a query (e.g. `Rose`) and want to search for a category (e.g. `Rose tag:Music`), the space after the query gets removed when auto-completing.

	<details>
	<summary>Video</summary>
	<img src="https://user-images.githubusercontent.com/2109929/94856055-b913f900-042f-11eb-9832-0ae4b27c9ba5.gif" />
	</details>

#### Web Browser and Version

Google Chrome 85.0.4183.121 (Offical build) (64-bits) 

#### Operating System and Version

Windows 10 OS Version 2004 (Build 19041.508)

#### Screen Resolution

2560x1080

**Comment by velddev** [comment]
Thanks for your feedback! We'll let you know when they're resolved :)

**Comment by velddev** [comment]
These have been resolved.
