### ISSUE TITLE
Search Bar Sorting(mobile) + Offline Bots

### ISSUE THREAD

**Issue by Luc1412** [top-gg/issues#430]
#### Suggestion

I found 2 "issues" regarding to the new search engine.

Result sorting on mobile:

When I use the search bar on a phone, servers always get featured above the bots in the pop-up. It might be better feature bots on the main page first. On `/servers` search bar it should be as it's now. coul

Offline Bots in Pop-up:

The search engine should either only display online bots or bots which no longer offline than x days. I sometimes get bots which are offline for more than a year.

#### Applicable Links or Attachments

Image related to the first issue:
![Screenshot_20201002-072620.jpg](https://user-images.githubusercontent.com/24532065/94927305-5ddf1680-04c2-11eb-8f91-9bb9157ca150.jpg)

**Comment by velddev** [comment]
These should be fixed; we don't remove offline bots, but sort them by activity.
