### ISSUE TITLE
Tag list goes off the page

### ISSUE THREAD

**Issue by h-exx** [top-gg/issues#431]
#### Expected Behavior

Should show all the tags and maybe even add a scrollbar to it

#### Observed Behavior

Tag list went off the page

#### Applicable Links or Attachments

![](https://i.imgur.com/TusnKdx.png)

#### Steps to Reproduce

1. Open top.gg
2. Click on a bot (that you own)
3. Press Edit
4. Try to add a new tag

#### Web Browser and Version

Chrome (Latest Stable)

#### Operating System and Version

Windows 10 Pro

#### Screen Resolution

1920x1080

#### Additional Information/Comments

N/A

**Comment by h-exx** [comment]
Wondering if this is fixed yet

**Comment by Hopefuls** [comment]
Yeah is likely fixed cc @Xetera

**Comment by Xetera** [comment]
This shouldn't be an issue anymore now that you can input custom tags you want instead of scrolling through a huge list of presets.
