### ISSUE TITLE
New role for experienced coders and helpers in the Discord Bot List server.

### ISSUE THREAD

**Issue by ExtremeDevelopments** [top-gg/issues#435]
#### Suggestion

Create a “helper” role that gives users with the role permissions to do certain tags in the support and development channels for when mods are not there to help. This would be helpful because many times users will do something wrong in these channels and we cannot use presets to direct them to the correct channel in a correct and nice way. 

If the tag usage role is created, possibly add language/library divisions. 
Example: 
-py [tag name]
-js [tag name]
These will respond to the user with the answer to a common question which would be what the tag name is. This can give the user better information with the pictures it can contain and the way the embed is formatted.

**Comment by ExtremeOps** [comment]
Let me know if you have any questions <3 :)

**Comment by Faith1sGay** [comment]
How you would judge if someone is "experienced"?
Experience is a very very very subjective term. 
Like for example, I could say that I am experienced with node for the past like year and a half, but someone else might say that isn't experienced at all.

Also I think it would bring a big divide in the community because also the mods / admins could gatekeep the role. 

I mean of course they could set a standard for the "level of experience", but even then, lets say they set the standard at 1 year. Ok, that's fair, but that doesn't mean that person has any clue what they're doing.

**Comment by ExtremeDevelopments** [comment]
Maybe more of a "Message history/Checking the user's past messages in support channels? Then have a quick interview or application in direct messages verifying they know what they are doing. It could also be done that people can use tags but then there is a 'tag restriction' role if users abuse tags so they just can't use them anymore

**Comment by Faith1sGay** [comment]
I mean, what number would you suggest be the number of message history to check for? 
100? 1000? 10,000?

One of my friends is a certified dev on dbl and hes only sent 1 message (because i pinged him kek), and hes extremely knowledgeable in programming.

**Comment by ExtremeDevelopments** [comment]
I mean you could also get it like:
Verified Bot Developer Badge, Verified Bot, Certified Bot on top.gg, or message history, or with other reasons like contributions in other servers and/or message history in other lib servers

**Comment by Faith1sGay** [comment]
I mean some people dont have a verified bot or bot dev badge, and they've been programming for over a year, like me.

**Comment by Xignotic84** [comment]
This isn't something we want to add currently, the reason for this is that the way we would chose people is through subjective means and people would complain or get annoyed for not having the role. It would end up with people just wanting the role instead of trying to actually help others.
