### ISSUE TITLE
suggestion for Discord server list tags 

### ISSUE THREAD

**Issue by Kaesu2975** [top-gg/issues#436]
**It could have a label called furry, as furry are a community of animals with human characteristics and some of them have fantasies. I had to check Animal Crossing because this game is a little closer to the furry fandom and the server that is published is not Animal Crossing but Furry fandom. Just as there is a kpop fandom tag there must also be a furry fandom tag**
![image](https://user-images.githubusercontent.com/72667781/95662446-62807c00-0b0d-11eb-91a1-e4f00c197e45.png)
![image](https://user-images.githubusercontent.com/72667781/95662453-73c98880-0b0d-11eb-8ca8-ae24a4faa5b3.png)

**Comment by Xetera** [comment]
I'll be closing this as we have a new user-defined tags system planned for sometime next month.
