### ISSUE TITLE
Minor issue with Webhook URL entry.

### ISSUE THREAD

**Issue by Team-Woo** [top-gg/issues#441]
#### Suggestion

Can the default webhook URL be changed to be http not https? Since https doesn't seem work with all libs(or at all? not sure.)
Might be the cause of some confusion.

#### Applicable Links or Attachments

[User potentially misled](https://discordapp.com/channels/264445053596991498/412006692125933568/765662483759104050)
![image](https://user-images.githubusercontent.com/65966213/95910208-b1c4e780-0d6d-11eb-8303-9117d101cc67.png)

**Comment by Xetera** [comment]
It's not the job of the library to support https, you should be using a reverse proxy like [`caddy`](https://caddyserver.com/) or [`nginx`](https://www.nginx.com/) to route traffic to the right port/container. This might be something that can be addressed in more detail in the upcoming new docs™ but I would like to keep the placeholders `https` to encourage best practices.

**Comment by velddev** [comment]
On that note if you don't have the ability to receive webhooks or don't want to do https; use a service similar to https://www.webhooks.io/. They seem to have plenty of usecases.
