### ISSUE TITLE
Scrolling background

### ISSUE THREAD

**Issue by steadmatthew** [top-gg/issues#443]
#### Suggestion
Remove the scrolling background on the /user/:ID path. This starts to use **a lot** of CPU/GPU very quickly.

##### Chrome
There's no difference on the default scrolling and the custom scrolling images, they both use a lot of CPU power. Around 50-60% on an i7-8750H

##### Microsoft Edge
There is a difference between the two. Custom scrolling images easily maxed out an Intel(R) UHD Graphics 630, while the default scrolling uses 65-75% of it. 

I don't know if this is a correct result, but it seems to be using about 25% of my GPU (a GTX 1060) on default scrolling and on a custom  scrolling background it uses around the same (Note: this is on a laptop and the results were taken with task manager).

##### Edge on 1060 (Default)
![Edge running on 1060 with the default scrolling image](https://jeremy-clarkson.is-inside.me/8uoxCJ0k.png)
##### Edge on 1060 (Custom)
![Edge running on 1060 with a custom scrolling image](https://jeremy-clarkson.is-inside.me/n207tB8X.png)
##### Edge on integrated graphics (Default)
![Edge running on integrated graphics with default scrolling image](https://jeremy-clarkson.is-inside.me/A2XDrrFv.png)
##### Edge on integrated graphics (Custom)
![Edge running on integrated graphics with custom scrolling image](https://jeremy-clarkson.is-inside.me/32809yOC.png)
##### Chrome (Default)
![Default scrolling image on chrome](https://jeremy-clarkson.is-inside.me/Sw330wo3.png)
##### Chrome (Custom)
![Custom scrolling image on chrome](https://jeremy-clarkson.is-inside.me/xSArF9IR.png)

**Comment by steadmatthew** [comment]
very right is the GPU (apart from in the chrome custom one)
very left is the CPU

**Comment by Xetera** [comment]
This has been an issue on our backlog for a while now. It seems to happen on specific kinds of hardware regardless of browser due to a combination of `animation` and `box-shadow` properties on the banner, not because of the animation by itself.

I've spent some time investing this but it's difficult to replicate and we'll most likely get rid of the entire thing when we redesign the user page in the near future anyways.

**Comment by steadmatthew** [comment]
👍 Thanks!
