### ISSUE TITLE
Search by library doesn't work

### ISSUE THREAD

**Issue by Luc1412** [top-gg/issues#444]
#### Expected Behavior

When searching library: discord.py it should list me all bots with the given library

#### Observed Behavior

It showed no result.

#### Applicable Links or Attachments

![Image 1](https://i.imgur.com/hurmROJ.png)
![Image 2](https://i.imgur.com/rIzjkhX.png)

#### Steps to Reproduce

1. Visit a Bot written in Discord.py
2. Click on the Discord.py text. The Website will redirect you to search
3. The Not found error occurs 

#### Additional Information/Comments

There is also no suggestion for search by library as in the past.

**Comment by Xetera** [comment]
The search system was changed earlier and this functionality wasn't ported to the new api because the majority of users do not use it (since they're not developers). This will not be re-added and the button for functionality will be removed soon.
