### ISSUE TITLE
Won't appear in profile

### ISSUE THREAD

**Issue by Zenolian** [top-gg/issues#446]
After I authorized it and it arrived in my server I went to my profile and that exact server is not appearing DSL isn't working this is a really annoying bug

**Comment by Xignotic84** [comment]
This is a known issue with DSL due to discord rejecting our application for intents on the DSL bot. The way we discover servers is going to change this week and problems with adding servers will be fixed.

**Comment by Xignotic84** [comment]
Moved to #447

**Comment by Zenolian** [comment]
How did you get my email???
