### ISSUE TITLE
Server not in my Profile after add the Bot to the Server

### ISSUE THREAD

**Issue by Wuppertaler93** [top-gg/issues#447]
#### Expected Behavior

I added the Bot DSL to my server and see nothing in my Profile

#### Applicable Links or Attachments

![Image of the Profile](https://mylonky.eu/bugs/1.png)
![Image of the Server](https://mylonky.eu/bugs/2.png)
[Link to My Profile](https://top.gg/servers/me)

#### Steps to Reproduce

1. Open top.gg/servers/me
2. Klick on Add a New Server
3. Add the bot to my server
4. go back to top.gg/servers/me

#### Web Browser and Version

Firefox 81.0.1 (64-Bit)

#### Operating System and Version

Windows 7 (64-Bit)

#### Screen Resolution

1920x1080, 1360x768, 1280x1024 and 800x480 (Yes 4 Monitor)

#### Additional Information/Comments

I dont now why it not work

**Comment by MrNeverSleep** [comment]
I have the exact same problem

**Comment by Xetera** [comment]
This should be fixed now for server owners, if you're not the owner but have administrator privileges, there's a fix coming for this (along with a feature for adding servers more easily) later today.

If you are the owner, kick DSL and reinvite it and you should be able to get it to work then.
