### ISSUE TITLE
Unable to view profile on mobile website

### ISSUE THREAD

**Issue by Latkecrszy** [top-gg/issues#449]
#### Expected Behavior

I expected to be able to access my profile on the mobile top.gg website

#### Observed Behavior

Instead I was not able to access my profile on the mobile top.gg website 

#### Steps to Reproduce

1. Open top.gg on an iPhone. (The problem may extend to android, but I am not sure)
2. Log in.
3. Click on the 'hamburger' icon, or 3 lines in the top right hand corner.
4. Scroll down, and attempt to click on your username.

#### Link to screen recording

![examplegif](https://user-images.githubusercontent.com/66486461/97817832-bc2f1e80-1c53-11eb-9296-d0f1a27ffee4.gif)

#### Web Browser and Version

Safari 14

#### Operating System and Version

iOS 14.2 Beta

#### Screen Resolution

1334x750

**Comment by Xetera** [comment]
this issue should be fixed with the new condensed mobile menu
