### ISSUE TITLE
like removes base reviews count

### ISSUE THREAD

**Issue by oriapp** [top-gg/issues#453]
### Description

I have a one feedback on my bot, when i give it a like and refresh the page the "Based on x reviews" x changes to zero and also the starts.
Once i have removed it and refresh the page again it back to normal.

#### Applicable Links or Attachments

![Before i liked the feedback](https://i.imgur.com/2b6a6VU.png)
![After i liked the feedback](https://i.imgur.com/eRA8uT0.png)

#### Steps to Reproduce

1. Open top.gg
2. login 
3. go to some bot with one feedback that you own
4. give it a like
5. refresh 

#### Web Browser and Version

Chrome Version 86.0.4240.183 (Official Build) (64-bit)

#### Additional Information/Comments

It might don't work with more then one vote, or bot that you don't own

**Comment by Xignotic84** [comment]
I cannot replicate this, this may be caused by cache.

**Comment by oriapp** [comment]
> I cannot replicate this, this may be caused by cache.

yeah maybe, not 100% sure. but better to take a look

**Comment by velddev** [comment]
This is a caching side-effect; intentional.
