### ISSUE TITLE
You can vote multiple times.

### ISSUE THREAD

**Issue by freddierick** [top-gg/issues#455]
#### Expected Behavior

Vote once

#### Observed Behavior

Vote as many times as you like 

#### Steps to Reproduce

1. Open top.gg
2. Click a bot 
3. vote
4. refresh

#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 98 SE

#### Screen Resolution

320×240

#### Additional Information/Comments

If you vote, then refresh the page you can vote again instantly; this may not impact the total votes but it does send a webhook out every time. This is an easy fix if you give rewards using a bot (just add a lastVoteTime field to your database); however, this has just injected like 50k into my bots economy.

**Comment by Xignotic84** [comment]
This issue should have been fixed earlier.
