### ISSUE TITLE
Cant choose rating stars

### ISSUE THREAD

**Issue by Team-Woo** [top-gg/issues#459]
#### Expected Behavior
Clicking stars should select the right one.

#### Observed Behavior

Doesn't select any

https://i.gyazo.com/3fd7bbd9d4c8235d5d1d08157f81ae0c.mp4

#### Web Browser and Version
Chrome
Version 86.0.4240.183 (Official Build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

1440p

Someone reported it in #support not sure what hardware and browser.

**Comment by Xetera** [comment]
Fixed
