### ISSUE TITLE
Brave browser Mobile cannot submit reviews.

### ISSUE THREAD

**Issue by Team-Woo** [top-gg/issues#461]
#### Expected Behavior

Clicking submit submits review.

#### Observed Behavior

Clicking submit opens number keyboard.

#### Applicable Links or Attachments

https://youtu.be/6cwEyUE5Sg8
https://discord.com/channels/264445053596991498/714045415707770900/774014542471888947

#### Web Browser

Brave

#### Device

Samsung s10 and pixel 4

**Comment by Xetera** [comment]
Fixed
