### ISSUE TITLE
Unable to select star rating for new reviews system.

### ISSUE THREAD

**Issue by stageosu** [top-gg/issues#463]
#### Expected Behavior

User is supposed to be able to leave a proper star rating.

#### Observed Behavior

User clicks on star(s), but the rating does not stay.

#### Applicable Links or Attachments

[Video of bug](https://streamable.com/w0bfqj)
[Link to Kaguya Bot](https://top.gg/bot/538910393918160916)

#### Steps to Reproduce

1. Attempt to leave a review.
2. Click on star rating.

#### Web Browser and Version

Google Chrome on Mobile
Google Chrome on Windows | 86.0.4240.183 | 2020-11-03 (Also tried incognito)
Microsoft Edge on Windows 10 | 86.0.622.58 | 2020-10-30

#### Operating System and Version

Microsoft Windows 10 Pro
100.18363 Build 18363

#### Screen Resolution

2560x1440

#### Additional Information/Comments
(None)

**Comment by Xetera** [comment]
Fixed
