### ISSUE TITLE
I can't even vote at top.gg (country problem i guess)

### ISSUE THREAD

**Issue by alansyahdwi** [top-gg/issues#464]
I can't vote at top.gg, the ads won't appear. I already disabled all the AdBlocker, but still won't work.

I've tried to change to another Internet Connections, still won't work.

But, when I using VPN and trying to vote at top.gg, it works.

I think the problem is in the Country. The ads doesn't appear at several Country.

My country: Indonesia.

![Screenshot_386](https://user-images.githubusercontent.com/63584768/98309766-e68b2e00-1ffd-11eb-86d3-790ac79445b8.png)

**Comment by velddev** [comment]
Has this been resolved by now?
