### ISSUE TITLE
Ads for Top.gg/Poketwo

### ISSUE THREAD

**Issue by LazyGamer397** [top-gg/issues#466]
I've tried watching multiple ads and still can't vote. This is ridiculous and now I'll lose my freaking voting streak. We have PRIVACY for a reason. Consider adding a donation option for ad free voting and supply additional rewards such as pokecoins or a great-ultra box.

**Comment by Xignotic84** [comment]
Moved to #457

**Comment by LazyGamer397** [comment]
That doesn't help.

**Comment by LazyGamer397** [comment]
FIX YOUR DAMN SITE
