### ISSUE TITLE
Add check box in /edit: NORMAL VOTING

### ISSUE THREAD

**Issue by DomeQdev** [top-gg/issues#467]
Current voting system SUCKS. I watched 5 fucking anime videos, my eyes wants die, and NO VOTE BUTTON.

Add id /edit checkbox: **NORMAL VOTING**

**Comment by AwesomeStickz** [comment]
Or just add a skip button after 5 secs, this auto skip sucks, infinitely loading ads after ads, just add the button at least *facepalms*

**Comment by RaidAndFade** [comment]
I don't want auction credits, I want my users to vote. This will fix that issue.

**Comment by Xignotic84** [comment]
Moved to #457
