### ISSUE TITLE
ads can't be skipped and are nsfw

### ISSUE THREAD

**Issue by AlexIsOK** [top-gg/issues#470]
#### Suggestion

title

#### Applicable Links or Attachments

warning: age restricted

https://www.youtube.com/watch?v=ZC0ugcUZ8wo

**Comment by lwagf** [comment]
+1 I'm on chrome android and after skipping an ad, i'm just stuck on "recommended videos" that never end.

**Comment by stageosu** [comment]
+1

Here is a recording of trying to vote on my own bot: https://streamable.com/0rmjta

**Comment by velddev** [comment]
Hey, could you check if refreshing your browser cache for top.gg fixes this?

**Comment by stageosu** [comment]
https://drive.google.com/file/d/1mqGTiZSC90NlBWogovzDVTttm4WRF2kz/view

This was my attempt on an incognito tab.

**Comment by velddev** [comment]
Could you reach out to me on Discord? lets see if we can find the cause for your issue.

**Comment by velddev** [comment]
Should be resolved now. Ads listed here were reported and removed
