### ISSUE TITLE
Can't vote since today

### ISSUE THREAD

**Issue by LugiaDepression** [top-gg/issues#472]
#### Expected Behavior
Voting worked yesterday. Tatsu bot gives currency which I can't get any other way than voting on the bot regularly. It worked fine yesterday, I didn't update anything, auto updates are all blocked for me

#### Observed Behavior

But today i open it and there is an ad window with never ending ads. If I hit "back to tatsu" button then "vote" again the same happens, I can't vote

My friend has a better phone and they didn't change anything either but they can't even see the ads because their basic phone browser (the only one, Samsung ) has auto adblock which you can't turn off or if you can you won't because that's super unsafe to lower your phone security (especially for a vote which worked okay the previous day)

#### Applicable Links or Attachments

![Screenshot_20201106-092418](https://user-images.githubusercontent.com/24565263/98348298-d5034f80-2018-11eb-9806-3b4b95fb483e.jpg)
![Screenshot_20201106-092525](https://user-images.githubusercontent.com/24565263/98348311-db91c700-2018-11eb-93a6-f3ef6681ed88.jpg)
![Screenshot_20201106-092439](https://user-images.githubusercontent.com/24565263/98348324-e0ef1180-2018-11eb-8bc3-bc8df956ab84.jpg)
![Screenshot_20201106-100723](https://user-images.githubusercontent.com/24565263/98348339-e4829880-2018-11eb-89de-c92b7cab165e.jpg)

#### Web Browser and Version

We're both using Samsung phone browser

#### Operating System and Version

Samsung J5 & Asus Zs5

#### Additional Information/Comments

Please fix it, delete the ads and collect that money which you would get from the ads from the bot devs instead, it's tatsu's fault we're forced to vote for the cash because they made it so the users only can earn this kind of currency if they vote or bothers with a super expensive, time and energy consuming project of keeping a pet thing

**Comment by Xignotic84** [comment]
Moved to #457
