### ISSUE TITLE
Stop Making People Disable Ad-Blocker On Top.gg's Voting Pages

### ISSUE THREAD

**Issue by aashethepidgeymurderer** [top-gg/issues#481]
I Think Top.gg Should Stop Doing This As An Incognito Tab Is The Only Way For People To Vote Since People Get Trapped In Ad-loops. It Also Inconveniences People Who Vote Before School-Times To Keep Streaks. Pokemon Bots Making More From Votes + Other Stuff Could Turn Out Like **Pokecord** On Day. 
heres what i think:
![b7e4592ccb37879445343a086ca692f6](https://user-images.githubusercontent.com/74080330/98440917-90001b80-20f3-11eb-841a-e5cd04e33687.jpg)

**Comment by Xignotic84** [comment]
Moved to #457
