### ISSUE TITLE
Opt-in to vote for credit

### ISSUE THREAD

**Issue by johnyburd** [top-gg/issues#482]
#### Suggestion

I would like to be able to opt of the new credit for votes feature.  100% of my users have stopped voting for my bot because it's way too annoying to disable adblock and watch an ad.

My bot is not big enough for me to accrue any real credit, but the few hundred votes a month significantly helped my growth.

Possible implementation:
- instead of forcing users to disable adblock, simply don't count it towards my credit.
- let me decide not to show ads to vote (and don't give me credit for votes)

**Comment by Fyrlex** [comment]
That idea would be very good, but I think to prevent abuse, developers can only opt in and out at the end of every month and somehow top.gg would make sure they don't get votes counted over.

Also, you can easily get around the ad by using a VPN like Speedify.

**Comment by johnyburd** [comment]
That sounds reasonable.  As far as using a vpn, it needs to be easy for my users to care, so I don't think that'll help me much

**Comment by Xetera** [comment]
We have no intentions of making voting opt-in at the moment. Adblock restrictions have been lifted and we'll be adjusting the rewards to make it more useful to creators over the next few months.
