### ISSUE TITLE
ProBot vote page is always asking for captcha, Any reason?

### ISSUE THREAD

**Issue by Dramex** [top-gg/issues#484]
https://top.gg/bot/282859044593598464/vote

**Comment by Roki100** [comment]
lol, all i can think of is the votes being botted

**Comment by Dramex** [comment]
@Roki100 i'm thinking same, but it's been months now, it's not our fault if someone botted it for rewards. Anyway we already blacklists spammers and new users can't benefits from the rewards :-)

**Comment by Roki100** [comment]
no idea, but in general solving captcha each time can be annoying for bot users

**Comment by Dramex** [comment]
exactly, i'm asking for the removal of that captcha. it wasn't issue before the ads but after the ads users complains a lot. 
solving captcha, watching 5 second video. what a headache for small rewards

**Comment by FnrDev** [comment]
votes being botted 🤔

**Comment by Roki100** [comment]
> votes being botted 🤔

if you assume that is impossible, then yes it is possible

**Comment by FnrDev** [comment]
> > votes being botted 🤔
> 
> if you assume that is impossible, then yes it is possible

no it's not

**Comment by Roki100** [comment]
> > > votes being botted 🤔
> > 
> > if you assume that is impossible, then yes it is possible
> 
> no it's not

![fullbruh.png](https://user-images.githubusercontent.com/35699619/98950282-1738ff00-24f9-11eb-845f-4a5abd564c65.png)

**Comment by FnrDev** [comment]
> > > > votes being botted 🤔
> > > 
> > > 
> > > if you assume that is impossible, then yes it is possible
> > 
> > 
> > no it's not
> 
> ![fullbruh.png](https://user-images.githubusercontent.com/35699619/98950282-1738ff00-24f9-11eb-845f-4a5abd564c65.png)

ok 😆

**Comment by Xetera** [comment]
Probot is one of the bots we suspect is votebotting yes (or at least their users independently of probot itself). At some point the annoying hcaptcha feature is going to be replaced with recaptcha that will take your score into account first. Either way we do have plans for tweaking the botting protection to make it less frustrating for users

**Comment by velddev** [comment]
This has been resolved :)
