### ISSUE TITLE
Saying I'm a different user when going to a devs profile

### ISSUE THREAD

**Issue by SuperRicky06** [top-gg/issues#491]
#### Expected Behavior
Go to my profile to edit or see my bots

#### Observed Behavior

Takes me to the page I'm already on and saying "edit profile"

#### Applicable Links or Attachments

[Bots Page](https://user-images.githubusercontent.com/47152942/99138738-cf050400-2600-11eb-81a7-83ea3f99fd32.png)
[Owners Page](https://user-images.githubusercontent.com/47152942/99138749-ea700f00-2600-11eb-91c7-9a8a261ee17b.png)
[Top right hand corner](https://user-images.githubusercontent.com/47152942/99138759-f6f46780-2600-11eb-94cb-d4274217ffdd.png)
[What SHOULD happen](https://user-images.githubusercontent.com/47152942/99138772-0a9fce00-2601-11eb-85db-c61feabd8cf1.png)

#### Steps to Reproduce

1. Open top.gg
2. Go to a random bot
3. Click the bot owner
4. Click your name at the top right

#### Web Browser and Version

FireFox 82.0.3

#### Operating System and Version
Windows 10 Pro (v. 1909)

#### Screen Resolution

1920 x 180 (Smart TV HDMI)

#### Additional Information/Comments

I was just doing random stuff when I found this.

**Comment by Xetera** [comment]
fixed in new update
