### ISSUE TITLE
Rate of Bots being accepted

### ISSUE THREAD

**Issue by hrrstuart** [top-gg/issues#499]
### Suggestion for new Statistic on waiting for approval

I think there should be a new stat on the bot page beside below the 'Your bot is waiting for approval' (I am not making this suggestion because I'm impatient, I'm making it because I think it could turn to be very useful). It would have the rate at which bots are being reviewed in hours which would look like: **50 bots/hour**. There would also be something saying the total amount of bots that are currently ahead of the user which would simply just be like: **100 bots**.

If you want to see an example of how it would look like, go [here](https://cdn.discordapp.com/attachments/772502247266320435/779723758910570516/unknown.png)

**Comment by Xetera** [comment]
Currently our only rate of acceptance is found at https://p.datadoghq.eu/sb/islw0r99kwjgtwq8-0adf90d906730aacf47c4b7b12650942?from_ts=1605381171589&to_ts=1605985971589&live=true for which there'll be a direct link on the site to. We intentionally don't show how many people are ahead of you to prevent people from complaining about review orders and won't be implementing this.
