### ISSUE TITLE
Add OpenSearch to top.gg

### ISSUE THREAD

**Issue by AlexFlipnote** [top-gg/issues#501]
## Suggestion
Add **OpenSearch (Description XML)** to top.gg website. Would be much easier to use `TAB` button to search for bots or/and servers in a hurry. If you need a format example, [here you go](https://stackoverflow.com/questions/7630144/how-to-add-google-chrome-omnibox-search-support-for-your-site) (StackOverflow ftw) 🙂

## Applicable Links or Attachments
![Example image](https://i.alexflipnote.dev/5kQTZdA.gif)

**Comment by Xetera** [comment]
oooh this is great, I'm gonna be adding this

**Comment by velddev** [comment]
I always thought this was part of the JSON+LD search bar implementation, which was added earlier this month. This is really cool!
