### ISSUE TITLE
Add preview option for markdown

### ISSUE THREAD

**Issue by JeremyEspresso** [top-gg/issues#506]
#### Suggestion
The bot adding form should allow for previewing markdown. 

- This will make it easier to test out the markdown for the bot's description
- Reduce the number of edits by users for their description.
- Improve the user experience

This should improve the overall enjoyability of using markdown for a bot description on the website. 

#### Applicable Links or Attachments
N/A

**Comment by JeremyEspresso** [comment]
This currently exists only when editing a bot, however not when adding a new one

**Comment by Xetera** [comment]
The current way previews work relies on an existing bot page to function. Until the preview system is, changed which isn't something that's planned, this will not be implemented.
