### ISSUE TITLE
error responding

### ISSUE THREAD

**Issue by OF3K** [top-gg/issues#508]
When I respond to someone, I write the message and make a message and it writes me 404 not found, I would love for you to take care of it quickly.
Link: https://top.gg/bot/759761366633676840
Photo link: https://ibb.co/XbwZsx9
![Screenshot 2020-11-28 120932](https://user-images.githubusercontent.com/68546878/100499495-cec54680-3172-11eb-9242-56b43ea24d63.png)

Good day from OF3K#6666

**Comment by Xignotic84** [comment]
This is because no bot with the ID 759761366633676840 is listed on our site.
