### ISSUE TITLE
Misleading tags

### ISSUE THREAD

**Issue by sinkaroid** [top-gg/issues#517]
#### Suggestion

Lots of bots like this, and i will not embed here for offensive reason,   
the pic tells everything http://prntscr.com/vx1ax1  

also idk why that bot having so much tags, is maximal 6 or 7 afaik  
pls improve.

**Comment by marcorennmaus** [comment]
Please contact a moderator on our server about bots abusing tags like this. Game tags are generally excluded from the limit but you're only supposed to use tags that are actually related to the bot.
