### ISSUE TITLE
Add User Discriminators to Bot Reviews

### ISSUE THREAD

**Issue by Jeydin21** [top-gg/issues#518]
#### Suggestion

I think you should add the discriminator tags to bot reviews so the bot owner can track the user who reviewed down easily.

#### Additional Information/Comments

This could be used for multiple reasons, one could be to chat with the user that made a bad review in real-time instead of just leaving a bad comment that could easily be fixed, another could be to contact the person who made a fake review on your bot.

**Comment by Xetera** [comment]
User profiles will be updated to include connections to 3rd party apps like Discord later on but we're working towards moving away from being a Discord focused platform so discriminators will be removed everywhere on the site starting next year.

**Comment by Jeydin21** [comment]
But it's *Discord *Bot List how are you supposed to move everything away
just like that?

**Comment by marcorennmaus** [comment]
top.gg is no longer intending to be just Discord-related, the domain change to top.gg back in 2019 was literally the first step.

**Comment by Xetera** [comment]
Regarding your suggestion, usernames of reviews now link to profiles of the commenter to make finding users easier. We won't be changing everything overnight but you will eventually find more than just Discord content on top.gg next year
