### ISSUE TITLE
Server tags links doesn't work / returns 404

### ISSUE THREAD

**Issue by IamDwight** [top-gg/issues#524]
#### Expected Behavior

Tags listed under an individual server should correctly link to the actual tag page, not throw 404.

#### Observed Behavior

Clicking a tag (while viewing a server page) returns a 404 and is incorrectly linked to main top.gg page.

#### Applicable Links or Attachments

[Server page this happens on](https://top.gg/servers/453679812175724546)
[INCORRECT 'Phasmophobia' tag link](https://top.gg/tag/phasmophobia)
[CORRECT 'Phasmophobia' tag link](https://top.gg/servers/tag/phasmophobia)

#### Steps to Reproduce

1. Open individual server page
2. Click one of the tags not relevant to bots
3. Receive 404 error

#### Web Browser and Version

Firefox version 83.0

#### Operating System and Version

Custom Linux distro

#### Screen Resolution

1920x1080

#### Additional Information/Comments

N/A

**Comment by Xetera** [comment]
Thank you, this is now fixed
