### ISSUE TITLE
Add feature developer premium

### ISSUE THREAD

**Issue by seanjhatch** [top-gg/issues#531]
#### Suggestion

I've had idea that you might want to think about. You know how you offer premium to remove ads, I obviously can only speak for myself and a couple of people i've spoke to but we don't use the site often enough to have that monthly subscription personally. However, as a developer, I would be more than willing to pay to remove the ads from my page and the upvote page for my bot in order to give people a better experience when visiting the page. Ideally this would be a one time fee or a very small monthly one but either way I assume, it would be more than the ads make. What do you think about that?

**Comment by Xetera** [comment]
While I commend you for wanting to pay to give your users a better experience, this would be extremely unfavorable for us when it comes to larger bots. We'll be adding many more features to premium in the following year, including some that will probably work with the same concept of "get premium to give your users new features" but this is not something we can currently do with ads. Sorry.
