### ISSUE TITLE
Search not prioritizing bot names

### ISSUE THREAD

**Issue by dukeofsussex** [top-gg/issues#537]
#### Expected Behavior

Entering the exact bot name should return the bot as the first result in the search's preview dropdown.

#### Observed Behavior

Votes are prioritized?

#### Steps to Reproduce

1. Open [top.gg](https://top.gg).
2.1 Search for `dyno` or `mee6`.
2.1.1 Neither is returned as the first result.
2.2 Search for `steam`/`ace`/`automator`/etc.
2.2.1 The bot with the exact name isn't shown.

#### Web Browser and Version

Firefox 84.0.1

**Comment by Xignotic84** [comment]
Search is based off of vote momentum for the past week, and isn't directly based on the name or description. This behavior is intentional.
