### ISSUE TITLE
Add "Technology" Tag For Servers

### ISSUE THREAD

**Issue by TannerReynolds** [top-gg/issues#538]
#### Suggestion

Top.gg has a "Developer" tag, as well as tags for "Crypto" and "API". I think it'd be beneficial to also have an overarching "Technology" tag for servers. Many servers are tech servers but are not specifically for developing software, mining crypto, or are for any specific API. This would fit any and all communities that center themselves around computer hardware, cars, phones, Cameras, etc.

#### Applicable Links or Attachments

N/A

**Comment by Xignotic84** [comment]
We will be releasing user-defined tagging in the upcoming weeks/months, please wait for that instead.
