### ISSUE TITLE
The weird gitch edit page

### ISSUE THREAD

**Issue by CatAvoryYT** [top-gg/issues#540]
If you open bot edit page that has not been accepted and close the page and do it 15 or 20 Times then the page will look like this ![Screenshot_20210102-085531.png](https://user-images.githubusercontent.com/74831087/103458749-16db0a00-4cd9-11eb-8992-e9f5975b8c48.png)

**Comment by Xetera** [comment]
Maybe don't open and close your page 15 times? This is not the intended usecase of the site.
