### ISSUE TITLE
Servers with all caps are not visible when searching

### ISSUE THREAD

**Issue by ndbiaw** [top-gg/issues#541]
When your server has a all-capitalized name, it won't show up when searched. (Like "DISCORD" or "ALLCAP").

**Comment by velddev** [comment]
Do you have an example?

**Comment by velddev** [comment]
![image](https://user-images.githubusercontent.com/13852840/103459082-d4332500-4d0c-11eb-9bc1-a6358872a89e.png)

Top 2 here are all caps

**Comment by ndbiaw** [comment]
> ![image](https://user-images.githubusercontent.com/13852840/103459082-d4332500-4d0c-11eb-9bc1-a6358872a89e.png)
> 
> Top 2 here are all cap
My server, called EMULATION, has over 16k members and 200+ vote. I posted my server on top.gg but it didn't show up when searching until I changed my server name to Emulation.
