### ISSUE TITLE
Trusted Role

### ISSUE THREAD

**Issue by DragonDev15** [top-gg/issues#550]
# Suggestion

#### I think a Trusted role could be added to the top.gg support server. This role would be given to people that are active in the support channel. This role would enable people to use the Luca commands that arn't staff but are trusted. 
---
#### Requirements to get role:
- Active in #support
- Have knowledge
- Have experience with top.gg (Must have the **@ Bot Developer** role)
I do think that having it as a random role that can be given to users if they meet the requirements

> Alternative ways to get the role:
- Apply for it

##### Why I would like this added?
> It would be a helpful feature for when community members are helping others & there are commands they would like to use.

**Comment by Xignotic84** [comment]
We've added a Notable Members role to our server, we will be looking out for some of the things that you've mentioned above when providing people the role.
