### ISSUE TITLE
Website HTML (problem)

### ISSUE THREAD

**Issue by raunakrajadh** [top-gg/issues#554]
#### Expected Behavior

When adding the description for the bot, if we use the <code></code> tag, the text inside the tag should be printed as written.

#### Observed Behavior

While using the tag <code></code>, there automatically comes a space gap on the first line!

#### HTML Code

<code>
const top_gg = 'top.gg'
\n
const website = 'web'
</code>

#### Expected output

const top_gg = 'top.gg'
const website = 'web'

#### Observed output

 >  const top_gg = 'top.gg'
>
const website = 'web'

#### Web Browser and Version

Microsoft Edge Version 87.0.664.60 (Official build) (64-bit)

#### Operating System and Version

Windows 10 20H2

#### Screen Resolution

1920 x 1080

**Comment by Xetera** [comment]
Needs a screenshot or better explanation since github formatting is making this very difficult to understand. Also `\n` is not a line break in HTML

**Comment by raunakrajadh** [comment]
> Needs a screenshot or better explanation since github formatting is making this very difficult to understand. Also `\n` is not a line break in HTML

### Here is the code
<img src="https://media.discordapp.net/attachments/755031719811481601/802512477081829406/unknown.png">

### Here is the output
<img src="https://media.discordapp.net/attachments/755031719811481601/802512618422009856/unknown.png">

### Comment
Notice that there is a space before 👉 >rps

**Comment by Xetera** [comment]
This is the equivalent of doing

\`Some multiline
code with
single backticks
here\`

on Discord. Use `<pre>` for multiline codeblocks instead
