### ISSUE TITLE
Discord Status Webhook

### ISSUE THREAD

**Issue by DragonDev15** [top-gg/issues#561]
#### Suggestion

This would probably be a good addition for the Top.gg support server in the # Discord News channel

> Link: https://discord-status.red-panda.red/
> Link (No / Commands): https://discord.com/oauth2/authorize?client_id=662416455366737949&redirect_uri=https://discord-status.red-panda.red/auth/callback&response_type=code&scope=webhook.incoming

I do know the owner (Name: `Ben!#0002` ID: `255834596766253057`) & I trust the webhook as I do have it in my server.

I do think it would be a good addition to the Top.gg Support Server!

**Comment by Xetera** [comment]
We cannot add unvetted webhooks to the server just on someone's word alone. Also, it seems pretty counterproductive to use Discord to display Discord outage messages.
