### ISSUE TITLE
Unable to change the webhook for my server.

### ISSUE THREAD

**Issue by jxshhhh** [top-gg/issues#565]
#### Expected Behavior

I expected to be able to change the webook for my custom bot

#### Observed Behavior

Instead, I was prompted with an Error 504 (Gateway error) when putting in the link.
#### Applicable Links or Attachments

Photos of what happened:
https://media.discordapp.net/attachments/461869545611853834/805841750320218202/unknown.png?width=1058&height=664 (Showing what I did)
https://media.discordapp.net/attachments/461869545611853834/805842137660260422/unknown.png (Image of the error message)
#### Steps to Reproduce

1. Open top.gg
2. Click Discord Servers
3. Click your name in the top right
4. Choose a server a click "Edit"
5. Scroll down to Webhooks
6. Change the webhook info and auth key
7. Press submit.

#### Web Browser and Version

Using Google Chrome
#### Operating System and Version

Dell Inspiron 5500

**Comment by Xignotic84** [comment]
This issue has been fixed a while ago.
