### ISSUE TITLE
Cannot toggle Usage Data switch on a forced theme bot.

### ISSUE THREAD

**Issue by AlexIsOK** [top-gg/issues#566]
#### Expected Behavior

I can toggle it regardless

#### Observed Behavior

I cannot

#### Steps to Reproduce

1. toggle the switch on a forced theme bot

#### Web Browser and Version

Firefox 85

#### Operating System and Version

Windows 10 19042

#### Screen Resolution

1920x1080

**Comment by velddev** [comment]
Should be fixed :)
