### ISSUE TITLE
Weird bot not found page

### ISSUE THREAD

**Issue by oriapp** [top-gg/issues#568]
so once you open a page of an un-listed bot it shows a very weird (and ugly) (error page)?
#### Applicable Links or Attachments

![example](https://i.imgur.com/V8QeLh7.png)

#### Steps

open a https://top.gg/bot/4993832568224358201
This link (^^) Isn't valid. and the bot isn't listed at TOP.GG
it shows the bot card instead of error page

**Comment by Xignotic84** [comment]
This is intended as it's the 404 page on the site.
