### ISSUE TITLE
Getting Spammed by GET requests from top.gg to the Webhook, which the documentation says should do a POST. 

### ISSUE THREAD

**Issue by ashishjhanwar-bst** [top-gg/issues#574]
#### Expected Behavior

the votes webhook should only receive POST requests from top.gg

#### Observed Behavior

the votes webhook receives POST and GET requests from top.gg

#### Applicable Links or Attachments

![image of sample POST request to the webhook](https://cdn.discordapp.com/attachments/412006692125933568/809325069079674890/Screenshot_2021-02-11_at_12.41.00_AM.png)
![image of the unwanted GET request to the webhook endpoint, also from the same IP ](https://cdn.discordapp.com/attachments/412006692125933568/809325065433907250/Screenshot_2021-02-11_at_12.40.27_AM.png)
![image of the sample volume of the spammy GET requests](https://cdn.discordapp.com/attachments/412006692125933568/809325662179164170/Screenshot_2021-02-11_at_1.00.28_PM.png)

#### Steps to Reproduce

1. Just add a votes webhook to the bot dashboard
2. Check your logs 

#### Web Browser and Version

Not Applicable 

#### Operating System and Version

Not Applicable

#### Screen Resolution

Not Applicable

#### Additional Information/Comments
Not Applicable

**Comment by Xetera** [comment]
Thanks, this bug report helped us identify a bigger issue on our end with the legacy webhook delivery codebase. We'll try to have this one fixed up before next week 👍

**Comment by ashishjhanwar-bst** [comment]
Thanks @Xetera!

**Comment by ashishjhanwar-bst** [comment]
Hey @Xetera any progress on this?

**Comment by Xetera** [comment]
@DevYukine was supposed to be looking into this but we had to go figure out migration stuff instead. I think we should have time this week to fix this?

**Comment by Xetera** [comment]
This issue was fixed yesterday with the release of the new webhook worker which you can find here https://docs.top.gg/resources/webhooks.
