### ISSUE TITLE
10 what?

### ISSUE THREAD

**Issue by OofChair** [top-gg/issues#575]
#### Expected Behavior

I expected to find an amount next to my queue number. 

#### Observed Behavior

Instead, I just found this below: 

#### Applicable Links or Attachments

![Top.gg bug](https://user-images.githubusercontent.com/66800643/107656345-1035a000-6c52-11eb-9277-4f1c9de18d08.png)
The link to the bot can't be linked because it is not approved. 

#### Steps to Reproduce

1. Open top.gg
2. Locate your bot (which is being reviewed and has a percentage)
3. See the percentage without an amount

#### Web Browser and Version

Firefox 85.0.1 (64-bit)

#### Operating System and Version

Ubuntu 20.04.2 LTS

#### Screen Resolution

1920x1080

#### Additional Information/Comments

N/A

**Comment by OofChair** [comment]
I just checked it does not show for 10, 20, 30, 40, and 50 percent, but it shows for 60 percent.

**Comment by Xetera** [comment]
no, this was just fixed

**Comment by OofChair** [comment]
Ah ok 👍🏼
