### ISSUE TITLE
Words Missing

### ISSUE THREAD

**Issue by NotMarx** [top-gg/issues#576]
# Bugs 
This seems to be likely bugs but I found this on iOS and not sure if its affect other platform device as well.

![8EFA3552-2055-4DC1-9B9B-E041533E2D4F](https://user-images.githubusercontent.com/73813638/107661071-7a365f80-6cbb-11eb-9839-4ad3d76f362e.jpeg)

**Comment by Xetera** [comment]
What's the browser and version? can't replicate this issue on iOS latest

**Comment by NotMarx** [comment]
I’m currently using Google Chrome on my iOS device and the Google Chrome version from what I’ve checked, it’s version 87.0.4280.77.

**Comment by DragonDev15** [comment]
I've encountered that however using an iframe via iOS a re-fresh fixed it for me.
