### ISSUE TITLE
Not able to access BOT edit page

### ISSUE THREAD

**Issue by typhoon11** [top-gg/issues#578]
#### Expected Behavior

I am the owner of **RILP BOT** and want to edit the description.

#### Observed Behavior

When I am trying to edit my bot description and all clicking on the edit button it's giving me access denied.

#### Applicable Links or Attachments

![Image of the error](https://media.discordapp.net/attachments/714045415707770900/809759928742707211/unknown.png?width=886&height=452)
[Link to RILP BOT](https://top.gg/bot/718501137484873748)

#### Steps to Reproduce

1. Open top.gg
2. Go to profile
3. Click on the View Button under RILP BOT
4. Click on edit

#### Web Browser and Version

Microsoft Edge - Version 88.0.705.63 (Official build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

1366x768

**Comment by Xignotic84** [comment]
Are you still having this issue when you try to edit your bot?

**Comment by typhoon11** [comment]
Uhm no this problem is fixed but I am not able to reply to any reviews and I can't add any co-owners

**Comment by typhoon11** [comment]
I am still having the problem, I am not able to edit my bot
