### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by fatgum** [top-gg/issues#586]
#### Expected Behavior

Usually you log in and vote for a not and stuff 

#### Observed Behavior

But instead everytime I log in to try and vote for a bot, it doesn't log me in all!

**Comment by HaydenSynthetic** [comment]
Can confirm, logging in doesn't work at all site wide. Add a server button puts you in a url loop.

**Comment by velddev** [comment]
This is being looked into at the moment. Can you confirm that this happens for DSL only?

**Comment by WireSplitter** [comment]
I have the same issue. How can I verify that it's happening for DSL only?

**Comment by shikhinee** [comment]
It puts me in a loop to authorize discord then asks me to log in with discord again. Can't cast votes or add bots anymore. Using the latest Google Chrome on Windows 10. Tried clearing my caches and cookies, logging in from different devices. Still the same.

**Comment by WireSplitter** [comment]
Update: I was just able to vote on top.gg today. I didn't do anything differently, but logging in appears to work now

**Comment by Xetera** [comment]
This issue was fixed on tuesday

**Comment by WireSplitter** [comment]
Thank you
