### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by mrb23211** [top-gg/issues#593]
#### Expected Behavior

Login and Upvote Bots etc

#### Observed Behavior

Trying to login doesn't even log me in

#### Steps to Reproduce

1. Open top.gg
2. Try to login

#### Web Browser and Version

Google Chrome 88.0.4324.182

#### Operating System and Version

Windows 10 Home 10.0.18363

#### Screen Resolution

1920 X 1080

**Comment by ajsya** [comment]
Logging in isn't working for me either.

**Comment by DevYukine** [comment]
This should be fixed since some days :)
