### ISSUE TITLE
Add feature to exclude tags when searching bots

### ISSUE THREAD

**Issue by EasyThe** [top-gg/issues#600]
#### Exclude tags when searching bots

I think the feature to exclude some tags when searching bots would be a great addition because when I search for a bot I would like to filter out the bots that do not have english description/commands etc. Would be useful because there are a lot of turkish bots in the bot list.

**Comment by EasyThe** [comment]
Doesn't work
![image](https://user-images.githubusercontent.com/1358923/109744735-7a02f300-7bdb-11eb-94b3-61bc6610df3a.png)

**Comment by velddev** [comment]
It currently only works if this word is being used in the title or description. I'll look into if we can allow this for tags too later today.

![image](https://user-images.githubusercontent.com/13852840/109744937-6d7a9c80-7bd3-11eb-91ef-8c0942afee4d.png)
![image](https://user-images.githubusercontent.com/13852840/109744953-75d2d780-7bd3-11eb-81fa-2741963b8e78.png)
