### ISSUE TITLE
Adding GitHub webhooks to the #api channel

### ISSUE THREAD

**Issue by jpbberry** [top-gg/issues#602]
#### Suggestion

I think the Top.gg server should post either, all commits/prs/issues etc, or just releases, to the #api channel

Because it can
- Keep users update on what's going on behind the scenes
- Know when to update
- See real progress being made

**Comment by jpbberry** [comment]
Personally I'd like everything like commits and pr comments issues etc. But I can also understand why only releases would be better for not spamming.

**Comment by Xetera** [comment]
sounds good

**Comment by Xetera** [comment]
Just to make sure, you're talking about top-gg/issues and top-gg/node-sdk right?

**Comment by jpbberry** [comment]
I'd say any of the github packages under top-gg, node-sdk, issues, python-sdk, the sdk packages yeah

**Comment by jpbberry** [comment]
Maybe not /issues because a lot of the time it's not really API related hm

**Comment by jpbberry** [comment]
Closing as this is now implemented in the github-updates channel!
