### ISSUE TITLE
Paid Priority Queuing system for Bot Approval Applications

### ISSUE THREAD

**Issue by JohnTranQUT** [top-gg/issues#604]
# Suggestion

I believe there should be some kind of way where bot developers can pay to receive priority in the bot approval queue ..

- Profitable and makes it easier for Top.gg to pay their employees (bot approving moderators).
- Improve approval queue times.
- Bot developers who want to meet a deadline, will make use of the priority queue.

## How it could work

There would exist two (or even three) queues.

1. Normal bot approval queue
2. Priority Queue

Bot developers could opt into priority queue only if they have paid.
One would worry that the normal queue would never go down, however to better manage that, alternate the selection of bots to approve between the queues... e,g. One from normal queue, then one from priority, then one from normal again....

## Potential issues and mitigation plans

When priority queue is getting rather large, either charge higher or increase selection of bots in front of the queue to include more applications from the priority queue... e.g. 2 from priority than 1 from normal, 2 from priority and than 1 from normal and so on.

## Assumption made.

- The priority queue is usually shorter than the "Free normal approval" way.

Regards
AznDumbum (AznDumbum#7449 on discord).

**Comment by Xetera** [comment]
This is not something we're considering right now. We want to keep premium features accessible and useful to all users and this seems too unfair to the hundreds of devs who have no reason to get premium at the moment.

In the long run we want to keep queue closer to maximum 1 week anyways, so a priority queue wouldn't make much sense. It would lead to people buying premium for 1 month, submitting a bot and cancelling and getting ahead of everyone else which would be pretty frustrating for other devs.
