### ISSUE TITLE
Improve Team invites by providing Invite Url for faster joining (like Github)

### ISSUE THREAD

**Issue by kkrypt0nn** [top-gg/issues#615]
#### Expected Behavior

User who is invited gets a private message from Luca with a link to join the team he got invited to and the owner of the team can copy the invite link to send manually if the user has private message disabled.

If the user already gets a private message then let the owner copy the link from the team "dashboard".

#### Observed Behavior

Not found yet how to get in the team I got invited to.

#### Steps to Reproduce

1. Open top.gg
2. Create a team
3. Invite a member to the team

#### Web Browser and Version

Brave - 1.21.77 Chromium: 89.0.4389.90 (Official Build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

3440x1440

#### Additional Information/Comments

If there's a way to accept the invitation, please tell me ;-;

**Comment by Hopefuls** [comment]
What ID are you using to invite that member to your Team? A Discord-based User ID or top.gg ID?

**Comment by velddev** [comment]
Click on the edit profile button on your profile, then invitations

**Comment by kkrypt0nn** [comment]
> What ID are you using to invite that member to your Team? A Discord-based User ID or top.gg ID?

The user has been invited, it's showing pending.

**Comment by Hopefuls** [comment]
then do what veld said

**Comment by kkrypt0nn** [comment]
> Click on the edit profile button on your profile, then invitations

Will try that 👍

**Comment by kkrypt0nn** [comment]
After going to my profile and invitations it worked.

I would however recommend to add the ability to the team owner/admins to copy an invitation URL that the user just has to go on to axxept thr invitation. Would be much easier :)

**Comment by Hopefuls** [comment]
> After going to my profile and invitations it worked.
> 
> I would however recommend to add the ability to the team owner/admins to copy an invitation URL that the user just has to go on to axxept thr invitation. Would be much easier :)

This would definitely be a good idea
