### ISSUE TITLE
Remind me button not working

### ISSUE THREAD

**Issue by poop-creator** [top-gg/issues#617]
#### Expected Behavior

When clicking on the "Remind Me" button I expect it to be a button, I expect something it to say it will remind me, I expect to be reminded. 

#### Observed Behavior

Instead nothing happens. if I click on it 3 times the text "Remind Me" is highlighted, but it just acts like a piece of text as opposed to an actionable button. 

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/77906558/112709955-f06dda80-8e93-11eb-8714-8ae716fb4a2e.png)

#### Steps to Reproduce

1. Follow a vote link to top.gg 
2. click "vote"
3. try to click "remind me"

#### Web Browser and Version

Chrome
Edge

#### Operating System and Version

Windows 10

#### Screen Resolution

1366 x 768

#### Additional Information/Comments

Has been a persisting issue for me for longer than a month.

**Comment by velddev** [comment]
Should be resolved, not sure why it didn't work 🤔

**Comment by poop-creator** [comment]
> Should be resolved, not sure why it didn't work 🤔

well, I do notice that it was clicked for once, but it still got hung up like this. 
![image](https://user-images.githubusercontent.com/77906558/112740995-9cc0c700-8f4f-11eb-960a-b489544e8937.png)

P.S. thanks for the fast response, I should've said something sooner XD
