### ISSUE TITLE
User-info comand

### ISSUE THREAD

**Issue by Nathithegamer99** [top-gg/issues#622]
const Discord = require('discord.js')

module.exports = {
    name: 'userinfo',
    run: async (message, args) => { 
    const user = message.mentions.members.first()
    const embed = new Discord.MessageEmbed()
    
    .setTitle("User-info command")
    .setDescription("`Information about ${member}`")
    .setColor("#FF005B")
    .addField("Roles", user.roles.cache.map(role => role.toString()).join(" ,"), true)
    .addField("Account created", user.createdAt.toLocaleDateString("en-us"), true)
    .setTimestamp()
    .setFooter("user info")
    
        message.channel.send(embed)
    }
}

__problem__

Keeps saying can't define LocaleDateString
https://cdn.discordapp.com/attachments/817787874056994858/827453675601264640/Screenshot_20210402-100149_ASTRO.jpg

**Comment by GoogleFeud** [comment]
This has nothing to do with top.gg

**Comment by PrincessRavy** [comment]
coding on mobile generally is a crime

**Comment by LINKdiscordd** [comment]
this
