### ISSUE TITLE
Comments don't shown

### ISSUE THREAD

**Issue by xAvatar6969** [top-gg/issues#623]
#### Expected Behavior

I can read the comment in a bot page with custom wallpaper

#### Observed Behavior

I can't read comments in a bot page with custom wallpaper

#### Applicable Links or Attachments

[Image](https://imgur.com/a/AIBl64m)

#### Steps to Reproduce

1. Open top.gg
2. Open a bot with custom wallpapers
3. See comments

#### Web Browser and Version

Huawei Browser (for pc beta) 11.0.3.301

#### Operating System and Version

Windows 10 20H2

#### Screen Resolution

1920 × 1080

#### Additional Information/Comments

Nothing

**Comment by Hopefuls** [comment]
This is not an issue caused by top.gg, it is by the bot developer with their custom css. Reach out to them and inform them about it.

**Comment by xAvatar6969** [comment]
> This is not an issue caused by top.gg, it is by the bot developer with their custom css. Reach out to them and inform them about it.

Oh ok.
