### ISSUE TITLE
Moderator controls when adding bot

### ISSUE THREAD

**Issue by DragonDev15** [top-gg/issues#625]
#### Expected Behavior

Normally able to preview bot without moderator features. 

#### Observed Behavior

Moderator controls appear.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/70057141/113869889-960a3d80-97f4-11eb-8949-48035ef75390.png)

#### Steps to Reproduce

1. Open top.gg
2. Create a new bot
3. Fill it out and that should appear

#### Web Browser and Version

Chrome (N/A)

#### Operating System and Version

Windows 10

#### Screen Resolution

N/A

#### Additional Information/Comments

A bug that was pointed out in #support.

**Comment by takipsizad** [comment]
how do i enable it ?

**Comment by Hopefuls** [comment]
> how do i enable it ?
there is no need to, it isn't usable for normal users anyways.

**Comment by DragonDev15** [comment]
> how do i enable it ?

As @Hopefuls stated, its not useable however if you press preview it appears.

**Comment by DragonDev15** [comment]
I'm gonna close this

**Comment by kkrypt0nn** [comment]
Not happening only for new bots, visiting any bots will make it appear, see issue [696](https://github.com/top-gg/issues/issues/696)

**Comment by DragonDev15** [comment]
> Not happening only for newly added bots, visiting any bots will make it appear, see issue [696](https://github.com/top-gg/issues/issues/696)

969 is a dup of this one. It still appears....

**Comment by kkrypt0nn** [comment]
> > Not happening only for newly added bots, visiting any bots will make it appear, see issue [696](https://github.com/top-gg/issues/issues/696)
> 
> 969 is a dup of this one. It still appears....

Never said the opposite, you just specifically said it was for newly added bots:
![image](https://user-images.githubusercontent.com/43011723/118801216-0e0e5d80-b8a1-11eb-893c-3bf89a1759dc.png)

That's why I specified in my comment that it does not only appear for **newly added bots** but for all bots.

**Comment by DragonDev15** [comment]
> > > Not happening only for newly added bots, visiting any bots will make it appear, see issue [696](https://github.com/top-gg/issues/issues/696)
> 
> > 
> 
> > 969 is a dup of this one. It still appears....
> 
> 
> 
> Never said the opposite, you just specifically said it was for newly added bots:
> 
> ![image](https://user-images.githubusercontent.com/43011723/118801216-0e0e5d80-b8a1-11eb-893c-3bf89a1759dc.png)
> 
> 
> 
> That's why I specified in my comment that it does not only appear for **newly added bots** but for all bots.

Yes but...
![image](https://user-images.githubusercontent.com/70057141/118801808-c4476680-b8e4-11eb-85d0-ddad52f1eaea.jpeg)

**Comment by kkrypt0nn** [comment]
And that's why I specified in **this** issue that it was the same for all bots and not only newly added bots.

**Comment by Xignotic84** [comment]
This issue has been resolved.
