### ISSUE TITLE
Vote aint working

### ISSUE THREAD

**Issue by ShortfuseNO** [top-gg/issues#627]
#### Expected Behavior

I expected to press vote for servers, or bots.

#### Observed Behavior

Instead, it said i "voted" but nothing happend, i wasnt in the vote logs or anything at all, the bots that i "voted" for never gave me the rewards and the servers as well (for the servers the owner dmed me saying i didnt appear in the vote logs/Ticket logs.

#### Applicable Links or Attachments

(server voting image)
![image](https://user-images.githubusercontent.com/82161849/114039143-66057d80-987a-11eb-8013-69ec6bb2495d.png)
(bot OwO voting image) 
![image](https://user-images.githubusercontent.com/82161849/114039328-8e8d7780-987a-11eb-8cb6-5c4242ee90fd.png)

#### Steps to Reproduce

1. Open top.gg
2. go to the correct websites and vote 

#### Web Browser and Version

Microsoft Edge 89.0.774.68

#### Operating System and Version

Windows 10

#### Screen Resolution

1920x1080

#### Additional Information/Comments

I dont know what is happening i just know it says that the vote was completed but i dont get the rewards for the bots and for the server it doesnt say i voted and again the logs say i never voted.

**Comment by Hopefuls** [comment]
you already voted for these bots it seems like. A bot saying that you never voted does not mean you actually didn't. Try it again in 12-24 hours.

**Comment by ShortfuseNO** [comment]
> you already voted for these bots it seems like. A bot saying that you never voted does not mean you actually didn't. Try it again in 12-24 hours.

i did try to vote after 24 hours (to the server vote) it didnt work again it said in top.gg that i voted but nothing happend and the server owner checked the vote logs and i wasnt there

**Comment by ShortfuseNO** [comment]
problem is solved, i was using my alt log in instead of my main account, i apologise for disturbing u all with this,
