### ISSUE TITLE
Vote

### ISSUE THREAD

**Issue by RutviShah97** [top-gg/issues#633]
I cant vote any bot of discord.

**Comment by velddev** [comment]
Could you give more information?

**Comment by RutviShah97** [comment]
when i vote any bot it say you voted but it cant dm .

**Comment by velddev** [comment]
Make sure that you are:
- In a discord server that has the bot
- The bot has vote rewards
- Your DMs are open

These might be issues that could stop you from receiving vote rewards.

**Comment by RutviShah97** [comment]
I have all these

**Comment by Xetera** [comment]
A bot not being able to DM you is not a top.gg problem. If this is a problem you can reproduce with the webhook api, please create another issue that explains what you're doing along with the expected behavior.
