### ISSUE TITLE
Use new design button not applying changes

### ISSUE THREAD

**Issue by Rocky43007** [top-gg/issues#636]
#### Expected Behavior

Webpage when `Use new design` is enabled should be the one shown in the preview section.

#### Observed Behavior

Original normal webpage, even when enabled.

#### Applicable Links or Attachments

![Image of Option being Selected](https://cdn.discordapp.com/attachments/763432077940883469/833322974270586931/Screen_Shot_2021-04-18_at_3.46.55_PM.png)
![When clicking on preview](https://cdn.discordapp.com/attachments/763432077940883469/833322977172783114/Screen_Shot_2021-04-18_at_3.47.12_PM.png)
[Link to Botpage](https://top.gg/bot/815967191467163658)

#### Steps to Reproduce

1. Open top.gg
2. Go to your bot page
3. Go to the very bottom, underneath Website URL. Enable `Use new design`
4. Click Preview to check
5. Click Save.

#### Web Browser and Version

Firefox Nightly 89.0a1 (2021-04-14)

#### Operating System and Version

MacOS Catalina 10.15.5

#### Screen Resolution

MacOS Default Screen Resolution for 13 Inch.

#### Additional Information/Comments

Checked even with other browsers like Safari, Opera and Chrome

**Comment by Hopefuls** [comment]
This, well "issue", is known already, afaik it shows that on the Preview for developers to prepare their css for the new update. So that's intentional.

**Comment by Rocky43007** [comment]
Ah ok. Sorry for setting it as an issue then.

**Comment by Xetera** [comment]
We haven't enabled the new design for everyone so `Use new design` doesn't change your live page just yet. Soon™️
