### ISSUE TITLE
Hey, This is My Feedback :)

### ISSUE THREAD

**Issue by AdhamWalid** [top-gg/issues#643]
#### Suggestion

- Make the Review a Little Faster Since in My Opinion TOP.GG is How You Get Your Bot To Join 75 Servers and Get Verified Faster
- Try To Make The Website A Little Easier 
- Enable the Logs Channel To be Viewed For Everyione

#### Applicable Links or Attachments
That's It The Rest is Super Duper Cool!

**Comment by Hopefuls** [comment]
> Make the Review a Little Faster Since in My Opinion TOP.GG is How You Get Your Bot To Join 75 Servers and Get Verified Faster
Remember: Reviewers and Moderators (Staff in general) are volunteers. Simply saying "be faster" isn't an option as we do not invest our lives 100% into top.gg.

> Enable the Logs Channel To be Viewed For Everyione
They will probably be viewable pretty soon again, as far as I know myself.

**Comment by Xignotic84** [comment]
1. As Hope listed above, our staff team are made up of volunteers that work extremely hard to get through queue as fast as possible. We're always looking for new staff members and new ways to improve our process. 
2. Could you elaborate further in what you mean by "Try To Make The Website A Little Easier"?
3. I've gone ahead and reopened the logs channel to the public as we've made the changes necessary to reopen them.
