### ISSUE TITLE
New Design Page

### ISSUE THREAD

**Issue by InvalidWolf** [top-gg/issues#646]
#### Expected Behavior

Get to the normal top.gg main page 

#### Observed Behavior

I got an page with a guess the new Design

#### Applicable Links or Attachments

[Video](https://youtu.be/GyV7N6o6RIc)

#### Steps to Reproduce

1. Open top.gg/user
2. Click "Go Home"

#### Web Browser and Version

Google Chrome 90.0.4430.93

#### Operating System and Version

Windows 10 Home Edition

#### Screen Resolution

1920 x 1280

**Comment by flazepe** [comment]
Duplicate of #641.
