### ISSUE TITLE
Own bid automation out bidding youself

### ISSUE THREAD

**Issue by CPKreuz** [top-gg/issues#648]
So I just created a automation for a bid and then bid on that tag for a lower price, now the automation seems to have thought that some else bid and bidded higher for me

#### Steps to Reproduce

1. Create a bid automation for tag xy
2. Bid on tag xy for a lower price than the automation spending limit
3. See that the automation bid in the #bid channel on discord
3.1. May observe how 2 people are gonna react with a question mark to the message saying that you bid two times on the same tag like in this screenshot
[![](https://user-images.githubusercontent.com/45312141/116827808-589e9300-ab9b-11eb-8393-5a6100869920.PNG)](https://github.com/PixiEditor/PixiEditor)

**Comment by velddev** [comment]
Most likely what happened was that your webhook was faster processed than the other user's bid. 
![image](https://user-images.githubusercontent.com/13852840/116893782-a6fe7100-ac31-11eb-849d-00a1aa911b27.png)
