### ISSUE TITLE
404 and 405 issues

### ISSUE THREAD

**Issue by LugiaDepression** [top-gg/issues#649]
Can't vote, I getting 404 and 405 errors.

**Comment by Hopefuls** [comment]
First of all, please refer to ISSUE_TEMPLATES when making issues on our GitHub.

Second, please read #site-news in our Discord server for more information.

**Comment by LugiaDepression** [comment]
> First of all, please refer to ISSUE_TEMPLATES when making issues on our GitHub.
> 
> Second, please read #site-news in our Discord server for more information.

First of all?? There is the "New Issue" button but no issue templates button anywhere.
Second, I just tried and the issue is still present.

**Comment by Xetera** [comment]
We're looking into it

**Comment by DevYukine** [comment]
This is now resolved, next time you should take a look [at our discord server](https://discord.com/invite/dbl) to see status updates before making an issue here 👍
