### ISSUE TITLE
Unable to vote on Firefox.

### ISSUE THREAD

**Issue by ComfiestNeko** [top-gg/issues#650]
#### Expected Behavior

Show a vote button

#### Observed Behavior

The Vote button is not showing

#### Applicable Links or Attachments

Image of the vote button not showing: https://imgur.com/rpIrSxv

#### Steps to Reproduce

1. Open top.gg
2. Find some bot to vote
3. click on the vote button on the bot page
4. redirect to vote
5. vote button is not showing.

#### Web Browser and Version

Firefox 88.0

#### Operating System and Version

Windows 10

#### Screen Resolution

1920*1080

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by Xetera** [comment]
![image](https://user-images.githubusercontent.com/24978328/117008936-e4c3ce00-acf3-11eb-9cf4-802a44584726.png)
I was not able to reproduce your problem on firefox 88.0 on windows 10 with or without adblock

**Comment by Assassin-1234** [comment]
This happens because you have an adblocker on, its supposed to show an ad for a short time so either turn off the adblocker or wait for it to be over

**Comment by Xetera** [comment]
Ah yeah that makes sense, I just fixed the adblock issue in development a few days ago. You should be able to simply skip to voting with a "vote without turning off adblock" button immediately without waiting for the ad to load for 10 seconds. I'll let you know when I release the fix.

**Comment by ComfiestNeko** [comment]
> 
> 
> Ah yeah that makes sense, I just fixed the adblock issue in development a few days ago. You should be able to simply skip to voting with a "vote without turning off adblock" button immediately without waiting for the ad to load for 10 seconds. I'll let you know when I release the fix.

Oh okay, thanks!
