### ISSUE TITLE
You can't start a search query with #

### ISSUE THREAD

**Issue by YodaLightsabr** [top-gg/issues#652]
#### Expected Behavior

I expect to be able to start a search with a #, such as #bot.

#### Observed Behavior

It puts it as the URL hash instead of the search query

#### Applicable Links or Attachments

![Image of the cat](https://cdn.discordapp.com/attachments/714045415707770900/840980405951791134/unknown.png)

#### Steps to Reproduce

1. Open top.gg
2. Search for #anything

#### Web Browser and Version

Chrome Version 90.0.4430.93 (Official Build) (64-bit) Stable channel

#### Operating System and Version

Windows 10 Home 20H2

#### Screen Resolution

1920×1080

#### Additional Information/Comments

It would also be a cool feature to be able to search by tags, such as `#bot` if you wanted to search the bot tag, or `#music` to search the music tag. Maybe it would filter results to only bots that have that tag. Just a thought.

**Comment by NgXCyclone** [comment]
You do know there is a search feature to search tags right below the search bar? 
![image](https://user-images.githubusercontent.com/44649334/117579833-a57af000-b0ec-11eb-9727-149a28710da3.png)

not only that, the url to search tags as well is top.gg/tag/{tag} 

![image](https://user-images.githubusercontent.com/44649334/117579858-d0fdda80-b0ec-11eb-94e0-6b4680eb04bd.png)

**Comment by Hopefuls** [comment]
> You do know there is a search feature to search tags right below the search bar? 
> ![image](https://user-images.githubusercontent.com/44649334/117579833-a57af000-b0ec-11eb-9727-149a28710da3.png)
> 
> not only that, the url to search tags as well is top.gg/tag/{tag} 
> 
> ![image](https://user-images.githubusercontent.com/44649334/117579858-d0fdda80-b0ec-11eb-94e0-6b4680eb04bd.png)
> 
> 

Do not simply assume it being a wrong report, please attempt to reproduce it yourself

**Comment by Xetera** [comment]
We have a system coming up that improves the user experience of tag searches in specific without resorting to the hash symbol trick. I can confirm the behavior where search breaks when your query starts with a hash is fixed in the new version but we currently don't have plans to implement this style of tag searching in specific.

**Comment by goverfl0w** [comment]
If you're trying to search with tags, there is a subdirectory specifically designated for that as @Hopefuls and @NgXCyclone have respectfully said. Additionally, The `#` is regarded for URI fragmentation if you're trying to use the API, albeit you'll use the `?=&` key identifiers.

**Comment by YodaLightsabr** [comment]
> If you're trying to search with tags, there is a subdirectory specifically designated for that as @Hopefuls and @NgXCyclone have respectfully said. Additionally, The `#` is regarded for URI fragmentation if you're trying to use the API, albeit you'll use the `?=&` key identifiers.

The search query format is `/search?q=%s`. Not `/%s`. Even though `#` is for a URI fragment, it should in no way cause the search to be in a different format. It should be `/search?q=%23` if you search for `#`, because `#` gets encoded into `%23`. I never said there wasn't a way to search with tags; it was just an idea.

**Comment by YodaLightsabr** [comment]
Fixed. Verified on latest top.gg version.
