### ISSUE TITLE
Error logging into top.gg with discord

### ISSUE THREAD

**Issue by HadessDaughter** [top-gg/issues#655]
#### Expected Behavior

I expected to login top.gg with discord

#### Observed Behavior

Instead I found an error message (500)

#### Applicable Links or Attachments

[Screenshot of the error](https://i.postimg.cc/qqcHWk2W/errorr.png)

#### Steps to Reproduce

1. Open top.gg
2. Click on "login"
3. Press "Authorize" when the discord thing pops up

#### Web Browser and Version

Google Chrome

#### Operating System and Version

Windows 10

#### Screen Resolution

1920x1080

**Comment by velddev** [comment]
That's strange! I'll have a look into it. could you try again, does it always happen for you?

**Comment by HadessDaughter** [comment]
Yes, I've tried like 4-5 times, and always happens the same thing. I also tried logging off and onto discord again, but nothing changed.

**Comment by velddev** [comment]
Should be resolved now.
