### ISSUE TITLE
Premium page does not format correctly with color palette.

### ISSUE THREAD

**Issue by goverfl0w** [top-gg/issues#665]
#### Expected Behavior

The premium page should keep the same colors as with the rest of the website.

#### Observed Behavior

The premium page keeps the traditional greyple color.

#### Applicable Links or Attachments

![Image of the cat](https://i.imgur.com/ezBKFy6.png)

#### Steps to Reproduce

1. Open top.gg
2. Go to "Premium"

**Comment by Xignotic84** [comment]
This has been resolved as the page has been redesigned.
