### ISSUE TITLE
Cannot reply to reviews on bot pages (submits 0 star review instead)

### ISSUE THREAD

**Issue by pixxies** [top-gg/issues#671]
#### Expected Behavior

Expected to be able to reply to reviews. 

#### Observed Behavior

Site shows it's loading after hitting 
"Submit Reply" but doesn't load anything. After refreshing the page the reply has been posted as a separate review by the logged in bot owner. 

#### Steps to Reproduce

1. Open top.gg beta
2. Reply to a review. 

#### Web Browser and Version

Google Chrome 90.0.4430.210

#### Operating System and Version

OnePlus 7 Pro Android 11

#### Screenshot

![Screenshot_20210514-062214](https://user-images.githubusercontent.com/10077639/118220812-cb055200-b47c-11eb-98dd-4a6b2b9dd551.jpg)

![Screenshot_20210514-061730](https://user-images.githubusercontent.com/10077639/118220670-81b50280-b47c-11eb-8864-6fe6c47dda2c.jpg)

#### Additional Information/Comments

- It might be because I tried replying to a review on the second page of reviews.
- You cannot edit the bugged reply to add stars. 
- The bugged review with 0 stars does reduce the average star rating on the bot page. 
- You can delete this bugged review to revert the changes.

**Comment by goverfl0w** [comment]
Not able to reproduce but I only have 1 page of reviews which is to be noted.

**Comment by pixxies** [comment]
I can reproduce on my Desktop.

Bot page example: https://top.gg/bot/675996677366218774 (or any bot with 20+ reviews)

**Comment by goverfl0w** [comment]
Can't get it to show at all, can you provide a GIF or MP4?

![a](https://i.imgur.com/UeVnh5k.gif)

**Comment by goverfl0w** [comment]
Able to reproduce on desktop, seems to have a huge buffer issue.

**Comment by IacovlevMaxim** [comment]
Can reproduce on Desktop 
Web browser: Microsoft edge
Bot page: https://top.gg/bot/776897904404987946

**Comment by goverfl0w** [comment]
I'm sure they're already keeping track of Issues but will just ping @velddev anyhow.

**Comment by scottbucher** [comment]
Any update on this? This should really be addressed before the redesign is fully released.

**Comment by Xetera** [comment]
This is fixed. It might seem like it's not posting reviews because of caching issues that we're looking to solve currently but majority of review functionality is restored
