### ISSUE TITLE
Menu bar opacity (redesign)

### ISSUE THREAD

**Issue by asportnoy** [top-gg/issues#680]
#### Suggestion

The menu bar in the redesign has a transparent background and makes it hard to read when you're scrolled down on the page.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/14863373/118325131-a33bdb80-b4c8-11eb-8386-1e119f1e135c.png)

**Comment by velddev** [comment]
What browser do you use?

**Comment by asportnoy** [comment]
Chrome on macOS
