### ISSUE TITLE
edit button is visible in all of the bots

### ISSUE THREAD

**Issue by senor-init** [top-gg/issues#684]
#### Expected Behavior

edit button showing up if and only if you were a bot creator

#### Observed Behavior

edit button is visible for all bots  

![.](https://cdn.discordapp.com/attachments/710330953851076648/843115081612787752/bhth.PNG)

**Comment by goverfl0w** [comment]
The cat is very cute, but it doesn't show me if the bug is actually there.

**Comment by senor-init** [comment]
:kekw:



> 
> 
> The cat is very cute, but it doesn't show me if the bug is actually there.

**Comment by goverfl0w** [comment]
This issue is duplicate of #662

**Comment by senor-init** [comment]
ara
