### ISSUE TITLE
Replies to Reviews Also Count

### ISSUE THREAD

**Issue by NadieFiind** [top-gg/issues#687]
#### Expected Behavior
Replies to reviews on bot pages should not be counted in the "User Reviews".

#### Observed Behavior
When I reply to a review. The review count goes up. And the worst part is, it is counted as 0 star (maybe) which decreases the rating.

#### Steps to Reproduce
1. Reply to a review on a bot page.
2. See the review count and calculate the ratings if it is correct.

**Comment by marcorennmaus** [comment]
Duplicate of #685
