### ISSUE TITLE
Corruption votes

### ISSUE THREAD

**Issue by johann-lau** [top-gg/issues#691]
I would like to emphasise the voting problem. Whenever I go to top.gg, what I see is Mundae, Dank Memer, Mundae, Dank Memer and Mundae. This results from the extremely large number of votes for these bots. What caused this problem? Corruption. The bots on the top of the top-voted board offer rewards for voters - most likely rare ones - in order to lure users into voting for their bot every day.

I noticed that the bots are most likely currency-based bots. Those bots find it convenient to choose rewards for voters. After more users vote for the bot, it would go up on the top-voted board, and more users would discover the bot. Even more users would vote for the bot, and the vicious cycle continues. This make the top-voted board inaccurate and influences the clean bots.
It is possible to solve this problem. Here are some I can think of:

- Disallow bot owners from detecting votes through the API and Dashboard
- Limit the maximum votes per day
- (Am I insane? Please don’t think I am) Add a board for quality bots with few to no votes.

Thank you for paying attention to this issue and I sincerely hope you can find a way to stop the problem.

**Comment by LINKdiscordd** [comment]
I don't see an issue here.
Its a totally legit way to gain votes.

**Comment by Hopefuls** [comment]
This would ruin the purpose of why votes are a thing.

Some bot owners may disagree on that, but this would pretty much ruin the purpose of votes due to them being very useful to reward users with currency, aswell as being able to use vote credits in auctions to promote your bot.

If you really want your bot to be noticed without going a long way and without effort, consider using auctions.

**Comment by marcorennmaus** [comment]
Yeah, in my opinion implementing any of those changes would completely destroy the voting feature. 

A board for quality bots with few or no votes already exists, it's called [Certified](https://top.gg/list/certified). It *is* supposed to get removed soon, but a replacement for it was planned although at a very low priority.

**Comment by Xetera** [comment]
Votes is the way Top.gg does ranking on the site. It's not meant to be a measure of bot quality per se, but the popularity of the product and the activity of the users. Not everything is based on votes but they're the primary way we determine what is a top product by our standards. It's not a perfect system, we want it so people who spend the time to vote are rewarded for the effort while making sure bots with fewer votes don't disappear into obscurity.

Here are my thoughts on your points

> Disallow bot owners from detecting votes through the API and Dashboard

I don't understand what this would do to address the thing you claim is a problem. Do you want to make it inconvenient for people to check if someone voted? That just sounds annoying and not helpful in any way. This doesn't benefit bot owners who want to grow on Top.gg.

> Limit the maximum votes per day

How do we distinguish bots with very active userbases like mudae and dank memer from bots with moderate activity? These bots don't pull votes out of thin air (yes I've gone through the top list and checked every bot for suspicious activity), they have loyal users that use the bot reguarly. Why should they be punished for that?

> Add a board for quality bots with few to no votes.

This is something we've spent time thinking about and it's definitely coming. Votes aren't the only indicator of quality and we want to make sure other bots also have a chance of being in the spotlight without having to pay money in auctions. Certification wasn't the direction we wanted to go but something similar is definitely on the roadmap for smaller bots.

**Comment by moyshik7** [comment]
How else do you expect us to get votes or ratings ?  
I tried asking people nicely saying **Please leave me a vote. It helps us a lot**  
You know how many votes I got ?  
> 62 (actually I voted 10 moretimes that doesn't count)  
  
Then I made half my commands premium only and you can vote every 12 hours to enjoy premium benefits without paying.  
  
You know how many votes I got this time ?  
> 3.5k
  
  
Now I know there's nothing wrong in it

**Comment by johann-lau** [comment]
You are not a sincere person. Voting means agreeing with a bot, not wanting the premium features. Corruption is the real culprit that ruins the voting system. Open-source, or at least free, bots bring the best user experience since you don't have to do anything to use the commands. On the other hand, paywalled bots might not be _that_ good as they require users to pay for features. How often do you see free bots on the vote board? If you are not scrolling deep down, your answer would be "never".

**Comment by Xetera** [comment]
> How often do you see free bots on the vote board? If you are not scrolling deep down, your answer would be "never".

Ah I see what's going on here. Have you considered that maybe, just maybe, it's not the thousands of people who use, vote and pay for bots with premium features who are wrong, and that maybe it's just you?

Bots are free to offer any amount of premium commands as they wish. If people still choose to use use them and pay for premium, that's a pretty good indication to me that the features are worth it and that they belong higher on the vote leaderboard. Bots that paywall too many commands naturally sink to the bottom and bots that don't require any premium don't necessarily belong higher on the list either if they're not, you know... good.

Maybe someday you should try paying for things you use that people put countless hours into making.
