### ISSUE TITLE
Strange vote counter

### ISSUE THREAD

**Issue by Kobe118** [top-gg/issues#699]
There is a weird extra bit of text in the vote counter on my bot page:
![image](https://user-images.githubusercontent.com/32042747/118778849-ca105e00-b88a-11eb-905a-0197d469a3b9.png)

*edit: this is both for developers looking at their own page, as for regular users looking at different bots*

#### Brower & PC info

Opera 76.0.4017.123

Windows 10

1920*1080

**Comment by kkrypt0nn** [comment]
Same here.

**Comment by Xetera** [comment]
This is related to a bug with the new translations. It will be fixed today.

**Comment by Xetera** [comment]
This issue should be fixed now
