### ISSUE TITLE
"Direct Link" in place of "Website" button text | "Discord" in place of "Support server"

### ISSUE THREAD

**Issue by xMiyuka** [top-gg/issues#701]
#### Expected Behavior

"Website" used to be the text, now it says "Direct Link"
"Discord" in place of "Support server" (This seems more intentional than above)

#### Observed Behavior

Same as above.

#### Applicable Links or Attachments

![Screenshot](https://scs.twilightgamez.net/s4vCy.png)

#### Steps to Reproduce

1. Open top.gg
2. Goto a bot page
3. Mine as example: https://www.top.gg/bot/icarus
4. View button text

#### Web Browser and Version

Firefox, Brave

#### Operating System and Version

Win 10

#### Screen Resolution

1920x1080

#### Additional Information/Comments
N/A

**Comment by goverfl0w** [comment]
Where is the link for it?

![image](https://i.imgur.com/E5E41yn.png)

**Comment by jpbberry** [comment]
I don't really see how this is a bug, it's apart of the redesign and it was purposely made to be this

**Comment by Xignotic84** [comment]
This an intentional change.
