### ISSUE TITLE
No log out button (redesign)

### ISSUE THREAD

**Issue by asportnoy** [top-gg/issues#705]
#### Expected Behavior

I can log out from the redesign

#### Observed Behavior

There is no log out button

#### Applicable Links or Attachments

N/A

#### Steps to Reproduce

1. Turn on the beta
2. There is no button to log out

#### Web Browser and Version

Chrome 90.0.4430.212

#### Operating System and Version

macOS Big Sur

#### Screen Resolution

(2560 × 1600)

#### Additional Information/Comments

Only applies to redesign

**Comment by moyshik7** [comment]
You sure ?  
I can still see the logout button in new design. It has moved a bit.  
  
![Screenshot_20210520-232253_Chrome Dev.jpg](https://user-images.githubusercontent.com/58624651/119022419-7012b400-b9c2-11eb-9cca-7df93841d445.jpg)

**Comment by Xetera** [comment]
We have a new design coming for the logout flow that's much more intuitive

**Comment by asportnoy** [comment]
> You sure ?
> I can still see the logout button in new design. It has moved a bit.
> 
> ![Screenshot_20210520-232253_Chrome Dev.jpg](https://user-images.githubusercontent.com/58624651/119022419-7012b400-b9c2-11eb-9cca-7df93841d445.jpg)

Ah, I see it now. Didn't expect it to be there. Though it sounds like @Xetera already has plans to move it. Thanks!
