### ISSUE TITLE
Turning on beta dosen't turn on beta

### ISSUE THREAD

**Issue by moyshik7** [top-gg/issues#706]
### Expected Behavior

When I turn `Beta feature` from the bottom of the page it should turn into the beta mode instantly (or do a reload by itself)

### Actual result

It doesn't do anything (Made me feel like I did something wrong) When I reload the page it turns into Beta mode.
  
  
  
#### System
  
Android 10, Samsung Galaxy A20 and A50  
Windows 10 (64bit)  
  
#### Browser
  
Chrome Latest (both platform)  
  
  
  
  
Edit: Here's how it is. (IDK how to screen record on Desktop so I'm doing it on mobile)  
  
![preview_on_mobile](https://i.imgur.com/6Ta86Y9.gif)  
  
  
(The gif dosen't seem to be showing. Go to this link if you can't see the gif)  
[https://imgur.com/6Ta86Y9](https://imgur.com/6Ta86Y9)

**Comment by Gideon-foxo** [comment]
I am not fully sure this is really an issue? It is a 'beta' mode and its just that. In the grand scope of things it does not really matter if the beta does not apply instantly.

**Comment by moyshik7** [comment]
Bruh  
  
  
All they have to do is add  
```js
window.location.reload();
```
At the end of their function (guessing React)  
  
(Maybe after they add the cookies or something just a reload won't hurt)
