### ISSUE TITLE
Broken texts in sidebar (mobile)

### ISSUE THREAD

**Issue by moyshik7** [top-gg/issues#707]
![20210520_232030.jpg](https://user-images.githubusercontent.com/58624651/119022102-098d9600-b9c2-11eb-93e8-93bda40c9b2f.jpg) 
  
It shows things like

- `discovery.label`
- `actions.add-a-bot`
- `actions.add-a-server`
- `premium.label`
- `action.join-discord`

  
  
I think something went weirdly wrong here

**Comment by moyshik7** [comment]
It doesn't appear on Desktop.  
  
I tried on Windows btw

**Comment by Xignotic84** [comment]
Can you please check if the issue is resolved on your end?

**Comment by moyshik7** [comment]
Yea it's fixed. Thank you  
![SSnow](https://user-images.githubusercontent.com/58624651/119926531-675d4780-bf99-11eb-8cd6-e544ce944dc9.jpg)
