### ISSUE TITLE
Changeable Reply Boxsizes

### ISSUE THREAD

**Issue by mgam-is-dreamin** [top-gg/issues#708]
#### Expected Behavior

I was replying to one of my reviews on my bot and the reply boxes sizes should not be changeable.

#### Observed Behavior

I was able to change the size of the reply box, which at that point was just a visual, but when I wanted to submit the reply, it wouldn't let me. No error pop-ups or whatsoever.

#### Applicable Links or Attachments

[Video of this happening](https://imgur.com/a/HOpOgeU)
[Link to my bot](https://top.gg/bot/806842327083253760)

#### Steps to Reproduce

1. Open top.gg
2. Go to a bot that you own
3. Reply to a review
4. See the little lines in the bottom right hand corner
5. Pick and Drag it

#### Web Browser and Version

Opera GX - LVL2 (core: 75.0.3969.259)

#### Operating System and Version

Windows 10 64-bit

#### Screen Resolution

1536x864

**Comment by Xetera** [comment]
Draggable textareas are definitely a normal feature (it exists on this reply box I'm typing in right now) it shouldn't affect whether or not you can submit a reply and it should most likely have a max size but the reply box should absolutely be resizable.

**Comment by Xignotic84** [comment]
This is not an issue, the resizing of reply boxes are intentional. With regards to the issues you're having replying to reviews, this is a known issue and isn't related to resizing.
