### ISSUE TITLE
Grammar Error  

### ISSUE THREAD

**Issue by IrishYellow** [top-gg/issues#716]
#### Expected Behaviour

That all the ':' are after every example statement.

#### Observed Behaviour

The ':' is only in the first example statement.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/84847508/119759327-68d03680-beeb-11eb-8445-e76a82294b27.png)

#### Steps to Reproduce

1. Open Docs https://github.com/top-gg/docs/blob/master/content/libraries/python.mdx
2. Add a ':' to end of example
#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 10 Home

#### Screen Resolution

1920x1080

#### Additional Information/Comments

It is only a spelling mistake, The fix is attached.
[python.txt](https://github.com/top-gg/issues/files/6550809/python.txt)

**Comment by Faith1sGay** [comment]
I--- uh honestly didn't know that Netscape was even still a thing in 2020

**Comment by kkrypt0nn** [comment]
> I--- uh honestly didn't know that Netscape was even still a thing in 2020

Either he's a troll, or he's using a Browser from 2008. As this wqs the latest release.

**Comment by IrishYellow** [comment]
Is my error not serious enough?

**Comment by kkrypt0nn** [comment]
I mean:

1: The steps to reproduce are not what to do to fix the issue but it's how you can get it.
2: You could've just done a pull request [here](https://github.com/top-gg/docs) instead of attaching a text file.

**Comment by IrishYellow** [comment]
Sorry this is my first day on GitHub

**Comment by Xetera** [comment]
This is really not important in any way. Please don't go out of your way to raise issues with small punctuation inconsistencies like these that technically aren't even grammar mistakes.
