### ISSUE TITLE
Navbar transparence AND need more padding

### ISSUE THREAD

**Issue by verleuchtet** [top-gg/issues#718]
If you add a custom bg-image, the navbar will get transparent, that doesn't look good!
And please add a padding to the box of the writings and if you add an announcement, the footer of the announcement will be "PublishedMay 22, 2021", please do a space between Published and the month.

the following image shows what I mean with the navbar and where more padding is needed

![image](https://user-images.githubusercontent.com/67605386/119825196-fd8c6180-bef6-11eb-8dba-c642c39a8b1a.png)

**Comment by goverfl0w** [comment]
The website is being redesigned, I don't think this is probably going to be a priority of theirs to fix.

**Comment by Xetera** [comment]
The new site has an option for you to add a background image that doesn't look extremely obnoxious the way this does.

**Comment by verleuchtet** [comment]
> 
> 
> The new site has an option for you to add a background image that doesn't look extremely obnoxious the way this does.

Can you add an option that darkens the background image a bit?
