### ISSUE TITLE
navbar menu on the advertise page

### ISSUE THREAD

**Issue by br1ss** [top-gg/issues#720]
#### Expected Behavior
I expected the menu on the advertise page navbar.

#### Observed Behavior
I didn't see a menu on the advertise page navbar.

#### Applicable Links or Attachments
![](https://i.imgur.com/qhT357g.gif)
[Page Link](https://top.gg/advertise)

#### Steps to Reproduce
1. Open top.gg/advertise
2. Enable beta features
3. Click on navbar
4. Click menu

#### Web Browser and Version
Opera GX LVL2

### Screen Resolution
1920x1080

#### Operating System and Version
Windows 10 Home, Version: 20H2

**Comment by Xetera** [comment]
Opera gx's adblocking (and some adblockers + firefox's enhanced tracking protection) breaks the javascript bundle on the advertise page because it thinks the site is serving ads. There's really not much we can do about this for the time being other than renaming the page to something else
