### ISSUE TITLE
[Auctions] CPM bidding displayed wrong in overview

### ISSUE THREAD

**Issue by asportnoy** [top-gg/issues#721]
#### Expected Behavior

In the auctions overview tab, the "Total bid active" takes from the CPM bid spending limit.

#### Observed Behavior

Instead it takes from the price per 1000 impressions

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/14863373/120234239-2e350980-c21d-11eb-9544-9a8b76172525.png)
In this case it should say $35 for the overview

#### Steps to Reproduce

1. Go to auctions
2. Place a CPM bid
3. Go to the overview tab

#### Web Browser and Version

Chrome 90.0.4430.212

#### Operating System and Version

macOS Big Sur

#### Screen Resolution

2560 × 1600

#### Additional Information/Comments

Only applies to the new CPM bidding

**Comment by goverfl0w** [comment]
Total bid active to my understanding only calculates the sum of CPMs, and not the limits. The limit is there more so the website knows when to stop once the impressions have been met for the CPM.
