### ISSUE TITLE
Discord server Update

### ISSUE THREAD

**Issue by 60Jordangaming** [top-gg/issues#723]
#### Expected Behavior

I expected to Update my discord server On the website When I click custom Invite code 
 

#### Observed Behavior

Instead I Get this when I click save settings I get this error (Failed to create a new invite. Please try again or contact website administrators.)

#### Applicable Links or Attachments

![Image of the Issue](https://ibb.co/FWHz06j)

#### Steps to Reproduce

1. Open top.gg
2. go to your discord server settings 
3. Click create custom Link
4. Click save settings

#### Web Browser and Version

Safari 

#### Operating System and Version

MacBook Air Ios 14.6

#### Screen Resolution

13.3-inch (2560 × 1600)

**Comment by goverfl0w** [comment]
I can't view the image attachment that was sent. I'm also not sure what your steps are exactly on, so this is what I'm assuming you're trying to say:

1. Go to the server settings of your server on Top.gg
2. Add an invite link from your server
3. Save the server settings on Top.gg

When doing this, I cannot replicate the issue you're having. May you please be a little more specific?

**Comment by marcorennmaus** [comment]
Mirror (they linked to what is essentially an imgur album link):
![Mirror](https://img.marcorennmaus.de/IUzBAVL1)

This issue was supposed to be fixed on 29th June 2021 which is a few weeks after this got posted so I'll assume this issue isn't even one anymore. If it's still an issue, please reopen.
