### ISSUE TITLE
Recent search suggestions can only be clicked on the text

### ISSUE THREAD

**Issue by asportnoy** [top-gg/issues#724]
#### Expected Behavior

I can click anywhere on a search suggestion to open the page

#### Observed Behavior

Only the text on the suggestion can be clicked. Anywhere else just closes the suggestion popup without redirecting.

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/14863373/120392198-c2729f80-c2f5-11eb-8778-1b7daa3c16ab.png)

#### Steps to Reproduce

1. Open top.gg
2. Click on the search bar. If no suggestions pop up, search for anything and then repeat this step.
3. Click on a part of the suggestion with no text (yellow border in screenshot). Observe the popup closing without redirecting
4. Click on the search bar again and click on part of the suggestion with text (red border in screenshot). Observe as you're redirected to the search results.

#### Web Browser and Version

Chrome 90.0.4430.212

#### Operating System and Version

macOS Big Sur

#### Screen Resolution

2560 × 1600

#### Additional Information/Comments

This is the same issue that I had with #630, but I didn't know what the cause of it was then.

**Comment by Xetera** [comment]
Issues on the old site are not going to be fixed
