### ISSUE TITLE
Replys not working and are screwing up my rating :(

### ISSUE THREAD

**Issue by StayWithMeSenpai** [top-gg/issues#728]
#### Expected Behavior

I expected it to just replay to a rating

#### Observed Behavior

Intead it was counted as a rating with 0 start

#### Applicable Links or Attachments

![Image of the reply](https://i.imgur.com/tyyVorx.png)
[Link to MangaCord](https://top.gg/bot/751148743901970622)

#### Steps to Reproduce

1. Open top.gg
2. go to a bot you own and reply to a comment
3. should happen quite often as it happned to me 2 times in a row

#### Web Browser and Version

Chrome Version 91.0.4472.77

#### Operating System and Version

Windows 10

#### Screen Resolution

1080x920

**Comment by GrinderDeveloper** [comment]
It’s a known bug

**Comment by Xignotic84** [comment]
Duplicate of #671
