### ISSUE TITLE
Webhook Support

### ISSUE THREAD

**Issue by RealPukhraj** [top-gg/issues#738]
#### Web hook Suggestion 

I have an suggestion. please change the webhook method becz many user can't do custom webhook feature add the discord webhook feature like if some one need vote count or vote alert then they can direct copy paste discord channel webhook and they got what they want.

Like : 
![image](https://user-images.githubusercontent.com/80047424/123365106-3faad080-d593-11eb-92d4-249e59bc475f.png)

Support [Bot](https://top.gg/bot/802812378558889994) 

#### Improve Statistics Feature 

Recently I see a discord bot list they provide an api for each bot statics every user can see this
You can see my Bot Statics... [Real Stats](https://statcord.com/bot/802812378558889994) So Please we want this type stats for topgg please add it

**Comment by cheesycod** [comment]
1. This is a breaking feature if it replaces the current option. So if this is implemented, it should be added as an additional option
2. Your bot should ideally be hosted on a VPS which allows port forwarding. Most bots do this

**Comment by Xetera** [comment]
Adding this feature would open a pandora's box of customization option requests that were simply not interested in addressing.
Webhooks are meant for notifications to infrastructure you control and there are plenty of bots that forward webhooks to your discord server already.
