### ISSUE TITLE
Vote webhook only sends empty GET requests

### ISSUE THREAD

**Issue by qwertyquerty** [top-gg/issues#739]
#### Expected Behavior

It sends a post request with the included information

#### Observed Behavior

My webserver receives empty GET requests

#### Steps to Reproduce

1. Setup a basic webserver
2. Point the top.gg webhook at it
3. Simulate a vote
4. See that you received a GET request

#### Web Browser and Version

Google Chrome 91.0.4472.114

**Comment by goverfl0w** [comment]
What API wrapper are you working with?

**Comment by qwertyquerty** [comment]
None?? I'm just listening for the votes with a flask server. This has nothing to do with an API wrapper afaik.

**Comment by NMW03** [comment]
Do you send 2XX response code?

**Comment by Xetera** [comment]
![image](https://user-images.githubusercontent.com/24978328/125128747-22374400-e107-11eb-9681-0fdc23719354.png)
Can't replicate with test votes

**Comment by Xetera** [comment]
Doesn't behave this way with regular votes either. Considering that we get millions of votes, I would expect to be seeing more reports of this. If you're behind a reverse proxy like nginx or apache server, make sure you check your config.

**Comment by qwertyquerty** [comment]
I'm behind nginx but the config doesn't seem to have anything that would rewrite request types at all.

**Comment by qwertyquerty** [comment]
It was an issue with cloudfalre http -> https rewrites changing request types.
