### ISSUE TITLE
You can not delete reviews/comments on your discord server

### ISSUE THREAD

**Issue by ViperCod** [top-gg/issues#742]
#### Expected Behavior

You should be abled to delete comments/reviews on your discord server

#### Observed Behavior

It does not delete them and it just refreshes the page

#### Steps to Reproduce

1. Open top.gg
2. Go to your own discord server
3. Try to delete a review/comment

#### Web Browser and Version

Google Chrome 91.0.4472.114

#### Operating System and Version

Windows 10

#### Screen Resolution

1366 x 768

**Comment by ChillFish8** [comment]
I mean that makes perfect sense, you *shouldnt* be able to remove someone else's review, otherwise people could just delete any bad review or thing they didn't like.

The button to delete the review shouldn't really be there in the first place though

**Comment by Xignotic84** [comment]
You are not meant to delete other users reviews from your page, this is just a visual bug.
