### ISSUE TITLE
Bot issue

### ISSUE THREAD

**Issue by RoundingExplorer** [top-gg/issues#745]
#### Expected Behavior

I cannot find my bot, Hangout

#### Observed Behavior

I found the server

#### Steps to Reproduce

1. Open top.gg
2. Search `Hangout`

#### Web Browser and Version

Chrome 

#### Operating System and Version

Windows 10

#### Screen Resolution

idk

**Comment by ashpotter** [comment]
bro momento

**Comment by GrinderDeveloper** [comment]
It’s a known bug

**Comment by ashpotter** [comment]
> It’s a known bug

yeah its a know issue

**Comment by RoundingExplorer** [comment]
> bro momento

What?

**Comment by dluxe4444** [comment]
> > bro momento
> 
> What?

The issue is known already. Check pins of #support

**Comment by ashpotter** [comment]
> > > bro momento
> > 
> > 
> > What?
> 
> The issue is known already. Check pins of #support

yeah (https://ptb.discord.com/channels/264445053596991498/714045415707770900/841986487578001428)

**Comment by goverfl0w** [comment]
meow

**Comment by ashpotter** [comment]
> meow

nya
