### ISSUE TITLE
if u do not login and try to vote, then u login (because it says "u need to login to vote") then it gives the bot 2 votes

### ISSUE THREAD

**Issue by gamebotjs** [top-gg/issues#746]
#### Expected Behavior

The bot will get 1 vote

#### Observed Behavior

The bot gets 2 votes

#### Applicable Links or Attachments

how tf am I supposed to show that

[Link to my bot to test](https://top.gg/bot/785573425253974066)

#### Steps to Reproduce

1. Open top.gg
2. Go to any bot's top.gg page
3. Then click the vote button (without logging in)
4. Then login
5. Then vote

#### Web Browser and Version

Brave/Google chrome

#### Operating System and Version

Windows 10 Pro

#### Additional Information/Comments

it might be because it is still counting the votes when u are not logged in

**Comment by Xignotic84** [comment]
The reason for this is because votes count twice on weekends.
