### ISSUE TITLE
Bot 

### ISSUE THREAD

**Issue by Highdrys** [top-gg/issues#747]
#### Expected Behavior

I expected to find my bot MySuperBot

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

![Image of the cat](https://top.gg/images/error.jpg)
[Link to MySuperBot](https://top.gg/bots/mysuperbot)

#### Steps to Reproduce

1. Open top.gg
2. ...

#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 98 SE

#### Screen Resolution

320×240

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by goverfl0w** [comment]
I'm sorry, _what?_

**Comment by Xignotic84** [comment]
Please make sure to fill out the template completely and correctly.
