### ISSUE TITLE
cannot view login page

### ISSUE THREAD

**Issue by Setback24** [top-gg/issues#750]
#### Expected Behavior

I expected to find my bot MySuperBot

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

![Image of the cat](https://top.gg/images/error.jpg)
[Link to MySuperBot](https://top.gg/bots/mysuperbot)

#### Steps to Reproduce

1. Open top.gg
2. ...

#### Web Browser and Version

Netscape navigator 9.0.0.6

#### Operating System and Version

Windows 98 SE

#### Screen Resolution

320×240

#### Additional Information/Comments

It might be because I visited a non existing page

**Comment by o1w** [comment]
interesting
