### ISSUE TITLE
Incorrect response of vote check

### ISSUE THREAD

**Issue by nazmigorkem** [top-gg/issues#755]
```js
const res = await axios.get(`https://top.gg/api/bots/${botID}/check?userId=${userID}`, {
					headers: {
						Authorization: DBL_TOKEN,
				        },
			  });
console.log(res.data);			
```
#### Expected Behavior

Expected output of the code above to get `{ voted: 1 }` response if user has voted else we get `{ voted: 0 }`

#### Observed Behavior

Even though user has voted to the bot, the response is  `{ voted: 0 }`. 

#### Steps to Reproduce
   1- Send GET request with authorization header to the endpoint of top.gg `/bots/BOT_ID/check?userId=USER_ID`
   2- Print out response data

**Comment by xMyThoLoGyx** [comment]
Same, thanks for that!

**Comment by Xignotic84** [comment]
I believe that it can take up to around 5 minutes for votes to be counted through the use of the API which may be the issue in your case here.

**Comment by nazmigorkem** [comment]
> I believe that it can take up to around 5 minutes for votes to be counted through the use of the API which may be the issue in your case here.

It has been about 6 hours and I still get `{ voted: 0}`.

**Comment by xMyThoLoGyx** [comment]
> I believe that it can take up to around 5 minutes for votes to be counted through the use of the API which may be the issue in your case here.

The API doesn't work, I voted 9 hours ago and it still returns false. If I try to vote, it says I already votes.

**Comment by Xetera** [comment]
This is a known problem caused by the voting changes, we'll try to get this fixed before the end of the day. Sorry for the inconvenience

**Comment by nazmigorkem** [comment]
It seems issue is fixed at the moment. Thus, I'm closing this issue.
