### ISSUE TITLE
Bot Profile not showing after changing

### ISSUE THREAD

**Issue by Tagliatellelol** [top-gg/issues#758]
#### Expected Behavior

I expected my bot's new profile image to show.

#### Observed Behavior

Instead My bot's Avatar Doesn't show

#### Applicable Links or Attachments

![Link](https://top.gg/bot/819643325177921587)

#### Steps to Reproduce

Change your bot's avatar pic

#### Web Browser and Version

Opera GX core: 77.0.4054.257)

#### Operating System and Version

Windows 10 Pro

**Comment by jnsp-vsc** [comment]
![img](https://i.imgur.com/P3Vtl4T.png)

click on Refresh dada.

**Comment by Tagliatellelol** [comment]
Ahh ok thanks alot bro :)
