### ISSUE TITLE
Allow claiming credits as real money

### ISSUE THREAD

**Issue by MEZBATHEKING** [top-gg/issues#768]
Top.gg credits can be claimed as real money can be bringed in paypal or other payment method.

**Comment by Xetera** [comment]
This is something we've thought about in the past. In the long term we definitely want to be able to enable people to make money from their products on Top.gg, but our team is way too small to get into handling payouts for creators right now which is a very challenging problem to tackle. If something goes wrong, it can directly affect creators financially and I definitely don't want that to happen. We also need a bigger anti-abuse team for this as allowing credits to be claimed as real money will be a huge incentive for fraud and we're going to need a way to deal with that too.

Definitely still on the table for the future but it's not something we've planned for just yet.

**Comment by MEZBATHEKING** [comment]
Ty
