### ISSUE TITLE
Footer has contact us written twice 

### ISSUE THREAD

**Issue by Woofer21** [top-gg/issues#769]
#### Expected Behavior

The 2 columns in the footer should have different names

#### Observed Behavior

The columns in the footer have the same names 

#### Applicable Links or Attachments

![Image of the issue](https://i.imgur.com/FqWgA8P.png)

#### Steps to Reproduce

1. Open top.gg
2. ...

#### Web Browser and Version

Version 91.0.4472.164 (Official Build) (64-bit)

#### Operating System and Version

Windows 10 64-Bit (10.0.19043)

#### Screen Resolution

1920x1080

#### Additional Information/Comments

Not sure if this happens on all of the pages, this screenshot is from my bot page (ill updated this if I have more info)

**Comment by velddev** [comment]
Fixed this :)
