### ISSUE TITLE
Site is not opening 

### ISSUE THREAD

**Issue by Barun7009** [top-gg/issues#771]
Is this host error or my internet problem 

![Screenshot_2021-07-28-10-02-45-24](https://user-images.githubusercontent.com/79396348/127264500-4dc43129-7208-45b4-92b5-8cf69256008e.jpg)

**Comment by geetanshpancholi** [comment]
I was about to post this too! Not working for me as well :((

**Comment by streepje8** [comment]
For me it only works when im not logged in. (it works in incognito until i log in).
Im not even getting the 504 it just times out.

**Comment by Xignotic84** [comment]
This should be resolved, this was likely caused to an outage with our provider.
