### ISSUE TITLE
I cant edit my bots page

### ISSUE THREAD

**Issue by Dhaloi** [top-gg/issues#772]
#### Expected Behavior

I expected to edit my bots page

#### Observed Behavior

I cant edit my page and see screen of pain

#### Applicable Links or Attachments

![Image of the cat](https://i.imgur.com/62ouMVn.png)
[Link to bot](https://top.gg/tr/bot/772831987240271903)

#### Steps to Reproduce

1. Open top.gg
2. Go to profile
3. Open your bot
4. Try to edit but see 500 error.

#### Web Browser and Version

Chrome **92.0.4515.107**

#### Operating System and Version

Windows 10 Pro

#### Screen Resolution

1920x1080

#### Additional Information/Comments

A guy named Learway is experiencing this about 4 months and I experiencing that 2 months.

**Comment by marcorennmaus** [comment]
Hey, are you still having this issue?

**Comment by Xignotic84** [comment]
This issue should have been resolved with the recent fix mentioned in #site-news.
