### ISSUE TITLE
Language selector should not use flags

### ISSUE THREAD

**Issue by Johannes-Andersen** [top-gg/issues#774]
#### Suggestion

Using flags for language selector is a known bad practise 

Language != Country/Flag

Austria, Belgium, Germany, Liechtenstein, Luxembourg and Switzerland all have German as one of their first languages. Why was none of their flags chosen? 

Same with the American flag, could we instead chose, let's say Sierra Leone 🇸🇱. Their official language is English

<img width="221" alt="Screenshot 2021-07-29 at 01 34 05" src="https://user-images.githubusercontent.com/57638117/127413488-8a9c19af-cc50-465f-87fc-6eab691475ea.png">

**Comment by Xetera** [comment]
We do actually replace the american flag with the English speaking country you're from if you're from let's say, the UK. That's a fair point overall though, the idea was to make it easier to distinguish languages in the dropdown. Maintaining flags for languages is also somewhat tedious so it would be convenient for me to get rid of them if it doesn't hurt user experience.

**Comment by Johannes-Andersen** [comment]
Here are some articles:
https://www.smartling.com/resources/101/language-selector-best-practices/
> Avoid flags unless content is specifically tailored to that individual country.

https://usersnap.com/blog/design-language-switch/

> So, why you shouldn’t use country flags:
> 
> There are design limitations if you use more than 20 languages for your app. Displaying 20 country flags can be quite messy.
> Countries do not represent languages, nor the other way round.
> Flags symbolize nations, not languages. It’s that simple.
> 
> And I recommend to only use country flags if your product is different from country to country and not from language to language.

https://scrybs.com/blog/language-switcher-best-practices/

> Using country flags, however, is usually quite a sensitive topic as it can touch on a number of cultural issues. Flags represent countries which cannot define a language. Many languages are spoken across countries. If you were to use flags to represent languages, which flag would represent English? Should it be the Union Jack or the Stars and Stripes? The same can be said of Arabic and Spanish. Some people may take offense for having to select the flag of a country they don’t identify with but share a common language.

There are a lot of good design options if you google "language selector best practices"

**Comment by Xetera** [comment]
I'll look into changing this once the new language picker design is completed, thanks for the heads up.
