### ISSUE TITLE
Cannot vote

### ISSUE THREAD

**Issue by Dooozor** [top-gg/issues#784]
#### Expected Behavior

Click on the vote button, let it the bot authorise my account, click on the vote button again and have my vote registered.

#### Observed Behavior

Instead I had a stroke trying for the 20th time letting the bot authorise me for it not to work

#### Steps to Reproduce

1. Open top.gg
2. Do the vote process
3. Get the sign in message

#### Web Browser and Version

Chrome latest stable release

#### Operating System and Version

Windows 10

#### Screen Resolution

1940 x 1260

**Comment by Xignotic84** [comment]
The issue should be resolved.
