### ISSUE TITLE
"Find Bot" button does not seem to work

### ISSUE THREAD

**Issue by moyshik7** [top-gg/issues#785]
#### Expected Behavior

The `Find Bot` button in [https://top.gg/bot/new](https://top.gg/bot/new) seems to do nothing and thus can't add any new bot/s.

#### Observed Behavior

The "Find Bot" button near the `Bot ID` input field does not seem to work

#### Steps to Reproduce

- Go to top.gg/bot/new
- Put the bot id and click on "Find Bot"

#### Web Browser and Version

Google Chrome

#### Operating System and Version

Windows 11, 10

**Comment by Xignotic84** [comment]
Could you clear your cache and attempt to do this again and also check your bowser's network calls to see if any calls are made?
