### ISSUE TITLE
Bot analytics not loading at all (504 error)

### ISSUE THREAD

**Issue by gamingbuddhist** [top-gg/issues#790]
#### Expected Behavior

I expected to see my bot analytics

#### Observed Behavior

I got a 504 error saying that the gateway timed out.

Error 504 Ray ID: 686e10af99073fd2 • 2021-08-30 12:36:31 UTC
Gateway time-out

You - Browser - Working
Toronto - Cloudflare - Working
top.gg - Host - Error

#### Applicable Links or Attachments

[Link to bot](https://top.gg/bot/865715952067149864)

#### Steps to Reproduce

1. Open top.gg
2. Click user profile
2. Click on bot
3. Click edit
4. Click on "Analytics"

#### Web Browser and Version

Google Chrome - Version 92.0.4515.159 (Official Build) (64-bit)

#### Operating System and Version

Windows 10

#### Screen Resolution

1920x1080

#### Additional Information/Comments

This started yesterday and continued into today.
Tried clearing cookies

**Comment by ExtremeDevelopments** [comment]
Followed your steps exactly and wasn't able to reproduce this.. http://img.extreme-is.me/6O1OQLuRpkDhPphr Got to the page perfectly doing same steps.

**Comment by Xetera** [comment]
This is most likely an inconsistent error. I'll try to address it before the end of the week.

**Comment by Xignotic84** [comment]
This issue should be fixed.
