### ISSUE TITLE
Accessing Profile from main page creates authorization loop.

### ISSUE THREAD

**Issue by Rocky43007** [top-gg/issues#791]
#### Expected Behavior

Clicking on the profile button takes me to https://top.gg/user/<user-id>

#### Observed Behavior

Does a Auth loop and just redirects to https://top.gg instead of redirecting to https://top.gg/user/<user-id>

#### Applicable Links or Attachments

[Video of Error](https://cdn.discordapp.com/attachments/763432077940883469/882251380130205708/Screen_Recording_2021-08-31_at_4.10.01_PM.mov)

#### Steps to Reproduce

1. Open top.gg
2. Log in
3. Click on Profile
4. Authorize
5. Click on profile again after redirect

#### Web Browser and Version

Firefox Nightly 93.0a1 (2021-08-30) (64-bit)

#### Operating System and Version

MacOS Catalina 10.15.7

#### Screen Resolution

2560 x 1600

**Comment by ExtremeDevelopments** [comment]
It is a known bug being worked on, the current fix as pinned in support is as follows:

How to login:
Login as usual. When it redirects you back to the top.gg website and prompts you to log in again, just refresh the page instead. You should now be logged in. 

How to logout:
Same as login. Click logout and then refresh the page. You should now be logged out.

**Comment by velddev** [comment]
Could you verify if this login loop is fixed? @Rocky43007

**Comment by Rocky43007** [comment]
Nope. Still happening. Just tested right now.

**Comment by Rocky43007** [comment]
Ok, fixed as of today.
