### ISSUE TITLE
Cant Login on top.gg

### ISSUE THREAD

**Issue by bariscodefxy** [top-gg/issues#793]
#### Expected Behavior

I trying login on top.gg but nothing happens when i try login.

#### Web Browser and Version

Google Chrome 92.0.4515.159 (Official Compile) (64 bit) Version

#### Operating System and Version

Windows 8.1 Single Language Build 9600

#### Screen Resolution

1920x1080

**Comment by Team-Woo** [comment]
When you login refresh the page, should solve this issue temporarily while a proper fix is released.

**Comment by ExtremeDevelopments** [comment]
Duplicate of #791, read the comment in there for how to fix

**Comment by bariscodefxy** [comment]
> When you login refresh the page, should solve this issue temporarily while a proper fix is released.

Thanks solved
