### ISSUE TITLE
Add twemoji support

### ISSUE THREAD

**Issue by Luke-6723** [top-gg/issues#797]
#### Suggestion

Adding twemoji support to top.gg long/short description.

Would allow easy use of emojis and adds site wide support for emojis on machines that may be missing font entirely.

#### Applicable Links or Attachments

![Example image](https://user-images.githubusercontent.com/80823011/132134444-7a776832-3001-4071-8e18-c6b606f96275.jpg)

**Comment by ExtremeDevelopments** [comment]
Twemoji script link: https://twemoji.maxcdn.com/v/latest/twemoji.min.js

**Comment by velddev** [comment]
Duplicate of #626
