### ISSUE TITLE
FAQ on the API

### ISSUE THREAD

**Issue by XkijuX** [top-gg/issues#80]
#### Suggestion

my suggestion is that we have a FAQ with the API because i had a hard time setting it up with webhooks and i didnt much much information about it. Therefore would a FAQ be really helpful

**Comment by Chewsterchew** [comment]
Good spot for a tutorial opportunity, API webhook tutorials or something

**Comment by Xetera** [comment]
This will be added in the new rework of the docs and developers will be able to add any extra tutorials they feel is necessary when api docs are open sourced.
Related to #231
