### ISSUE TITLE
voting spams requests to my webhook url

### ISSUE THREAD

**Issue by OfficialSirH** [top-gg/issues#800]
#### Expected Behavior

Not spamming my URL

#### Observed Behavior

When I voted for my bot with either a test vote or a normal vote it started spamming requests to my URL

#### Applicable Links or Attachments
When I voted once:
![My vote](https://i.imgur.com/pucOEIrm.jpg)
When I test voted once:
![My test vote](https://i.imgur.com/TFDWcO8m.jpg)

#### Steps to Reproduce

1. Open top.gg
2. Vote for a bot

#### Additional Information/Comments

I tested if it may just be bad vote handling on my end, but my vote handling worked perfectly fine with every other route

Also, even when I'd restart my bot right away to see if that'd stop the spam, it kept going so the only way for me to stop the spam was to completely shut my bot down for about a minute.

**Comment by Xetera** [comment]
You need to respond to votes with a 200 to acknowledge it otherwise it will retry thinking you didn't receive it successfully. https://docs.top.gg/resources/webhooks/#acknowledgement
