### ISSUE TITLE
Server Edit and Webhook pages bugged

### ISSUE THREAD

**Issue by Moquent** [top-gg/issues#801]
#### Expected Behavior

Bug 1 I expect it to go to my server listed on Top.gg when I click on the name in the analytics, announcements and the webhooks section of the edit server page. https://top.gg/ servers /776840845944291328

Bug 2 Show the navbar and the search bar seperately

#### Observed Behavior

Bug 1 Instead it goes to https://top.gg/ bot /776840845944291328
Bug 2 Instead it merges them both

#### Applicable Links or Attachments

![Bug 1](https://user-images.githubusercontent.com/63721912/132878423-37efd6dd-1f82-4a07-a9eb-fc6ddcb3ded6.png)
![Bug 2](https://user-images.githubusercontent.com/63721912/132880596-61a51298-6716-4a63-a1e8-a0a9a0359659.png)

#### Steps to Reproduce

Bug 1
1. Open top.gg
2. Go to the edit server section and choose a server
3. Click on either analytics, announcements or webhooks on the right section
4. Click on the server name which should take you to the server itself, but it won't due to the bug

Bug 2
1. Open top.gg
2. Edit server
3. Click on the webhook in the right section
4. You can see the search and nav bar merged

#### Web Browser and Version

Google Chrome 93.0.4577.63 (Official Build) (64-bit) (cohort: Stable)

#### Operating System and Version

Windows 11 Home

#### Screen Resolution

1920x1080

**Comment by MuhammadUsmanMithani** [comment]
Same here for me
Windows 10 Enterprise
1080p screen
MSEDGE v93
<img src="https://i.imgur.com/Wq6h0am.png" />

**Comment by velddev** [comment]
For bug 2, please make a new issue. Top level issue here has been fixed.

**Comment by Moquent** [comment]
> For bug 2, please make a new issue. Top level issue here has been fixed.

Yes, thanks, both were fixed.
