### ISSUE TITLE
[Feedback]: Option to tip bot reviewers

### ISSUE THREAD

**Issue by mahyarmirrashed** [top-gg/issues#802]
#### Suggestion

I think that we should add a feature that allows developers to tip the bot reviewers on the website. This could be done via direct PayPal or something more refined like Stripe when they submit their application. That way, the reviewers have more incentive to do better work and provide more meaningful feedback to the developers.

**Comment by darling** [comment]
Reviewers are volunteer positions with their own incentives and motivations being there.

Introducing a tipping system doesn't really make sense for a platform that has them filter and dictate the bots that are submitted for top.gg.

**Comment by mahyarmirrashed** [comment]
Good God you do not know how absolutely terrifying your profile is to me right now...
