### ISSUE TITLE
oauth2 DSL#8005 error

### ISSUE THREAD

**Issue by duongtuan303030** [top-gg/issues#804]
#### Expected Behavior

I expected to find my bot MySuperBot

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

oauth2 ![image](https://user-images.githubusercontent.com/80153297/133380853-ec2f5ba1-229a-4f64-9154-d40516bcc0ad.png)

oauth2 
https://discord.com/oauth2/authorize?client_id=422087909634736160&scope=bot%20identify&permissions=1&disable_guild_select=true&guild_id=810353161444261898&response_type=code&redirect_uri=https%3A%2F%2Ftop.gg%2Fservers%2Fnew%2Fsuccess

#### Steps to Reproduce

1. Open top.gg
2. go to add server 
3. add some server 

#### Web Browser and Version

Google Chrome | 93.0.4577.63

#### Operating System and Version

Windows 10 OS Version 2009 (Build 19043.1202)

#### Screen Resolution

320×240

**Comment by Xetera** [comment]
This issue should be fixed now.
