### ISSUE TITLE
504 error when submitting review reply

### ISSUE THREAD

**Issue by Cl00e9ment** [top-gg/issues#805]
#### Issue

When replying to a review on my bot page (https://top.gg/bot/761292824695013416), the request timeouts.
This issue is going on since many months.

#### Web Browser and Version

Tested on last version of Chromium and Firefox, with no extensions and with cache cleared.

**Comment by Cl00e9ment** [comment]
Seems like this bug has been reported many times now, but 4 months later it still isn't fixed. Shouldn't this bug be a priority since the comment system is an important feature of top.gg and it's currently broken?

- https://github.com/top-gg/issues/issues/671
- https://github.com/top-gg/issues/issues/714
- https://github.com/top-gg/issues/issues/741

**Comment by velddev** [comment]
The functionality has been resolved, the caching part has not.

**Comment by Cl00e9ment** [comment]
Indeed, the replies are working now. Thanks!
