### ISSUE TITLE
Backup the old design

### ISSUE THREAD

**Issue by lever1209** [top-gg/issues#814]
the propsed design doesnt sit right with me, wes wondering if you could pull a reddit and keep the old theme on there and call it retro or something (or a slow internet option because i have to wait a minute or two when loading a page, and the new design wont help)

**Comment by Xetera** [comment]
The main reason for the redesign was to get rid of the old technologies and code the site was built on top of that made adding new features to the site very difficult, so it definitely won't be coming back. Performance is a separate issue we're going to be addressing soon, we want to make sure the site is snappy on all device types.
