### ISSUE TITLE
Unable to save annoucement

### ISSUE THREAD

**Issue by MaskDuck** [top-gg/issues#816]
#### Expected Behavior

I expected my announcement to saved

#### Observed Behavior

I cant save announcement. It say sth went wrong

#### Applicable Links or Attachments

Nothing

#### Steps to Reproduce

1. Open top.gg
2. Go to announcement tab
3. Write an announcement
4. Save it

#### Web Browser and Version

Brave

#### Operating System and Version

macOS Monterey 12.0 Beta (21A5522h)

#### Screen Resolution

2560x1600

#### Additional Information/Comments

No!

**Comment by ExtremeDevelopments** [comment]
This is a known issue being worked on currently. There is not a ETA on the fix currently.
![image](https://user-images.githubusercontent.com/48730677/136130491-c81d986e-09fe-452a-8c6c-f71be98ed2a7.png)

**Comment by Hopefuls** [comment]
@Xetera this was resolved iirc

**Comment by Luke-6723** [comment]
Can confirm this is fixed. Although when creating an announcement it takes roughly 5-10 minutes to show up
