### ISSUE TITLE
Bot search is broken

### ISSUE THREAD

**Issue by 8auu** [top-gg/issues#834]
#### Expected Behavior

bots to be ordered by amount of votes in search results

### actual behavior

![image](https://user-images.githubusercontent.com/54277586/139458961-b8e28801-e694-4a71-8714-6f084faab14f.png)

**Comment by Xetera** [comment]
This was more or less addressed for the time being by making it more predictable for users. Search does not rely exclusively on votes (otherwise searching would be the same thing as the top bots list) and we're always looking for ways to improve it.

**Comment by 8auu** [comment]
If you do go down this road I feel as though the bots rating (reviews) should also be taken into account, many bots with less than 3 stars are appearing right at the top of the lists, and they also have fewer votes. Meaning the quality of the top bots in search results are pretty low. 

I do feel like votes typically are a good factor of displaying how good a bot is, even though at times they can be easily manipulated.

**Comment by bchurton** [comment]
You should also factor in the fact that smaller bots won't have the opportunity to grow if they do not get lots of votes. I know that my bot only gets 2-3 votes in a month and those are from me and it only has 2 reviews, so it wouldn't get a very high ranking. A possible way of sorting could be age of bot, such as if a bot is on the site for less than one week then give it a slight boost in the rankings.

**Comment by 8auu** [comment]
> You should also factor in the fact that smaller bots won't have the opportunity to grow if they do not get lots of votes. I know that my bot only gets 2-3 votes in a month and those are from me and it only has 2 reviews, so it wouldn't get a very high ranking. A possible way of sorting could be age of bot, such as if a bot is on the site for less than one week then give it a slight boost in the rankings.

2-3 votes a month isn't an excuse. You can vote for your own bot every 12 hours, meaning you can quite easily get a solid number of votes a month with a bit of time put into it.

**Comment by bchurton** [comment]
I know that, I was just giving an example. I just meant that some people don't really ask for votes (myself included) and even the top bots get only 300ish votes. My thought was just that factoring in the fact that newer bots won't be visible in tags and search etc if its based on votes and reviews etc, as getting people to vote and review let along add a bot that isn't visible is near impossible.

**Comment by bchurton** [comment]
Thats just my opinion and I'm not fussed if it gets added or not, its just something that they should take into consideration.
