### ISSUE TITLE
Bot displaying on profile but Not Found error on profile

### ISSUE THREAD

**Issue by prakarsh17** [top-gg/issues#842]
Bot displaying on profile but when I click on the profile or go to the voting page it shows not found error . WHy is it happening ? here are the screenshots
![image](https://user-images.githubusercontent.com/88645086/142805776-5fd3b948-d20e-436e-ba4d-94ecee1cde94.png)
![image](https://user-images.githubusercontent.com/88645086/142805784-c2942bdc-7dde-4a08-b87e-5a39d5699052.png)

**Comment by aeclgithub** [comment]
Has your bot been approved?

**Comment by prakarsh17** [comment]
that bot was deleted much time ago , now I added my new bot , But it is not approved yet. LINK https://top.gg/bot/916630347746250782
