### ISSUE TITLE
Bug issue

### ISSUE THREAD

**Issue by Darks213** [top-gg/issues#851]
I'm concerned on image guesser, my points are gone I don't know what happened I think it's a bugged please help me to recover my point is thankyou
![Screenshot_2021-12-10-00-31-38-46_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/95894137/145505407-de47415f-2561-4497-95ca-16eafdc0c682.jpg)

**Comment by faith-ie** [comment]
This has nothing to do with https://top.gg
