### ISSUE TITLE
Better Notification System

### ISSUE THREAD

**Issue by link-discord** [top-gg/issues#852]
#### Suggestion

When your bot gets approved you get a dm and an email sent to you (since top.gg already saves ur email). That way if you have ur dms turned off you still get notified by email. 

Additionally you could make it configureable so that you can choose either only email / dms or both

**Comment by Hopefuls** [comment]
The DM part is already done by Luca, though feel free to suggest it on https://feedback.top.gg/ aswell if haven't already.
