### ISSUE TITLE
Ratelimited 429 too many request

### ISSUE THREAD

**Issue by Musify1** [top-gg/issues#858]
### Getting this error
 
![image](https://user-images.githubusercontent.com/84908356/146715731-2d1a924a-d439-48e1-bcf1-3f2acb3e4c12.png)

_I will Post stats 3 to 4 time in My bot But After That I am Getting this error and I got This error Yesterday_ 

![image](https://user-images.githubusercontent.com/84908356/146715850-2937283c-4f15-441e-89de-ebb21610631a.png)
![image](https://user-images.githubusercontent.com/84908356/146715851-cc6f9f53-d0a9-484d-9aa8-db1946d95c4f.png)

**If AnyOne Know How to Fix Pls Help Me out to this problem**

**Comment by Luke-6723** [comment]
That's you being ratelimited.
Are you posting on an event or a set interval?

**Comment by Musify1** [comment]
i post stats on top.gg after that i am getting ratelimited

**Comment by Luke-6723** [comment]
How do you post stats, do you use a lib or do you post when your bot joins a server?

**Comment by Musify1** [comment]
i use eval command and it being posting stats after 30 mins

**Comment by Luke-6723** [comment]
Please ask for support in #topgg-api in the support server [here](https://discord.gg/dbl) so we can better help you

**Comment by Musify1** [comment]
I asked But they Say Ask Here

**Comment by Luke-6723** [comment]
@Musify1 who do you host your bot with

cc @Xetera unsure whats happening here, based on their logs they're online posting every 30 minutes, maybe you can help figure out whats going on. Might be a cloudflare things if they use a weird host but no idea

**Comment by Xetera** [comment]
You might be getting rate limited for other requests sent to the API. In general I recommend sending stats at most once an hour, but ideally it would be something like once every 12 hours. It's cached on the site anyways so you don't gain much from posting every 30 mins

**Comment by Musify1** [comment]
ohk I am Waiting 24hr To remove this error
