### ISSUE TITLE
Bot not submitting

### ISSUE THREAD

**Issue by Hitesh2700** [top-gg/issues#861]
i try to add my bot on top.gg website, when i click submit button, its just load and show submit button again without errors

**Comment by xWass** [comment]
You can try a couple of things to fix this. Check for very long tag names, as this can cause an issue with submitting. Also, check to see if you changed the preferred theme at the bottom. (I had mine changed to dark and the bot wouldn't submit.)

**Comment by Hitesh2700** [comment]
> You can try a couple of things to fix this. Check for very long tag names, as this can cause an issue with submitting. Also, check to see if you changed the preferred theme at the bottom. (I had mine changed to dark and the bot wouldn't submit.)

**Comment by Hitesh2700** [comment]
Thank you, the problem was i write very long tag names, thats why bot not submiting, once again, thank you, i am going close this
