### ISSUE TITLE
Widgets not displaying information

### ISSUE THREAD

**Issue by MarkoKupresanin** [top-gg/issues#862]
#### Expected Behavior

Widgets under the top.gg/api/widget endpoint display the server count and/or upvote count and/or owner.

#### Observed Behavior

The widget either does not load at all, or displays an error message saying something went wrong. 

#### Applicable Links or Attachments

![A widget from my bot](https://top.gg/api/widget/813634913885618197.svg)
![Image of the error message Large ver.](https://i.imgur.com/SaEp15p.png)
![Image of the error message Small owner ver.](https://i.imgur.com/RROQJvl.png)
![Image of the error message Large server ver.](https://i.imgur.com/3RKivKB.png)
![Image of the error message Large upvote ver.](https://i.imgur.com/uutwSTM.png)
![GitHub proof of error](https://i.imgur.com/Kfp2ccB.png)

#### Steps to Reproduce

1. Grab any of the widget links (Markdown or HTML5) provided at https://top.gg/bot/<your bot id>/widgets
2. Paste the code into a markdown or HTML file.
3. The error message in the image provided above will show up

#### Web Browser and Version

Chromium 96.0.4664.110

#### Operating System and Version

MacOSX Monterey 12.0.1

#### Screen Resolution

5120 × 2880

#### Additional Information/Comments

I'm not sure whether the api endpoint is sending back a 404, but the issue has been present to me for around 2 months. I tried looking for another issue about this and I did not find one, forgive me if this has already been brought to the development teams attention. (If I could improve on submitting issues please let me know because I have not made many before.)

**Comment by Hopefuls** [comment]
This is mostly caused by your bot not having a valid avatar on the site. Try refreshing data and waiting 30 minutes to an hour.

**Comment by MarkoKupresanin** [comment]
Thank you for the quick and clear response. I've tried this and it now works.
