### ISSUE TITLE
Weird comments on bot pages

### ISSUE THREAD

**Issue by Fenish** [top-gg/issues#868]
#### Expected Behavior

I expected to find my bot's comments instead of my friend's comments

#### Observed Behavior

Instead I found this cat

#### Applicable Links or Attachments

https://cdn.discordapp.com/attachments/714045415707770900/942918768802279454/opera_tO0Jj1tbwx.gif

#### Steps to Reproduce

1. Open top.gg
2. Go to any bot has comments i tried at [this](https://top.gg/tr/bot/724658095296479343) page
3. Go to search bar
4. Search any other bot i searched `ihni` [link](https://top.gg/tr/bot/921678503227822090)
5. check comments they are same

###Browser
Opera GX

**Comment by apenasigordev** [comment]
skill issue
