### ISSUE TITLE
Fix pls

### ISSUE THREAD

**Issue by RobloxGithub** [top-gg/issues#870]
While clicking on profile takes 10 mins to open.

**Comment by Luke-6723** [comment]
As far as I know this is known,

there is a workaround.

If you click on your profile, wait a few seconds and then back to the front page, then click on your profile it should work.

This is what I have to do anyway

![Example](https://img.pyrocdn.com/ReglHhnM.gif)

**Comment by apenasigordev** [comment]
Probably takes a while to render? Or something like this.

**Comment by kortzjwmerkt4ca** [comment]
helo discord web hook

**Comment by kortzjwmerkt4ca** [comment]
**nooooooooooooooooooooooooooooooo**

**Comment by apenasigordev** [comment]
?????
