### ISSUE TITLE
Fields for announcements too small

### ISSUE THREAD

**Issue by Domxnvk** [top-gg/issues#873]
#### Suggestion

Make the field for the content of the announcement larger. At the moment, the field is the same size as the title field, and it's a real pain to edit things there.

#### Why?

- It is too easy to slide the mouse pointer up and down
- More user-friendly editing
- Better text overview, especially useful for larger announcements

#### Applicable Links or Attachments

![image](https://user-images.githubusercontent.com/64827994/157052400-e8d6c31f-c410-4022-a600-2c92143fbc13.png)

**Comment by bchurton** [comment]
https://feedback.top.gg is the place for this, as this repo is for bugs and issues rather than suggestions

**Comment by Xetera** [comment]
Thanks for the feedback, I've updated the description to be more clear.
