### ISSUE TITLE
Bots are missing from all tags

### ISSUE THREAD

**Issue by sinkaroid** [top-gg/issues#877]
#### Expected Behavior

I expected to find my bot (724047481561809007) 10K votes

#### Observed Behavior

Bots still missing / does not appearing from all tags, idk why
when I find out, this guy also apparently lost his bot from all the tags: https://prnt.sc/4zCYDMkivGwh

I don't think it's the problem of the site being down recently, just a bit weird only some bots are missing

#### Additional Information/Comments

Hi top.gg, You have a plenty Discord mods, but no one answered me clearly

**Comment by Hopefuls** [comment]
Wish to give a quick heads up that us moderators are not developers on the site, we cannot give you insights on certain issues experienced on the site. Thanks for understanding ♥

**Comment by flav28** [comment]
Same for me for more than a week and they don't do anything about it...

**Comment by sinkaroid** [comment]
I've guessed, this issue will be fixed at the next month come. then it is resolved now
