### ISSUE TITLE
Top.gg doesn't work on Internet Explorer

### ISSUE THREAD

**Issue by faith-ie** [top-gg/issues#882]
#### Expected Behavior

Top.gg is completely broken on Microsoft Internet Explorer. 

#### Observed Behavior

for it to work

#### Applicable Links or Attachments

![iexplore_uIjxNiZsVj](https://user-images.githubusercontent.com/49874713/161277845-c4026c72-d1bd-4d77-99fb-3a7e0116047f.png)

#### Steps to Reproduce

1. Open top.gg in internet explorer 

#### Web Browser and Version
All internet explorer versions

#### Operating System and Version

Windows 10

#### Screen Resolution

1920 x 1080

**Comment by DolceJ0Lly** [comment]
Use a another browser

**Comment by link-discord** [comment]
> We do not support any version of internet explorer.

Im pretty sure it was meant as an april fools joke

**Comment by Hopefuls** [comment]
> > We do not support any version of internet explorer.
> 
> Im pretty sure it was meant as an april fools joke

That's sad to hear :(. I would've appreciated Netscape support on top.gg.

**Comment by 777777dl** [comment]
📢 200$ in $GADO Giveaway with Gādo NFT!

Monetize your gaming experience with #GadoNFT on #Solana ⛩️

✅ ❤️ RT & Tag 2 Friends
✅ Follow @GadoNFT & @MintOfTheDay🔔

⏰ 1 winner - 24h!

#SolanaGiveaway #NOTIGANG https://t.co/Cmmw6Mdq4C

**Comment by faith-ie** [comment]
What

**Comment by apenasigordev** [comment]
I believe that in the next few years no website will work in Internet Explorer...

**Comment by link-discord** [comment]
There are websites that work with IE??

**Comment by apenasigordev** [comment]
> There are websites that work with IE??

I think only Bing

**Comment by faith-ie** [comment]
No lmao even Bing is broken

**Comment by apenasigordev** [comment]
wtf
