### ISSUE TITLE
Note for Reviewers available after approval

### ISSUE THREAD

**Issue by link-discord** [top-gg/issues#890]
#### Expected Behavior

The field is not visible anymore

#### Observed Behavior

Instead the field is still available

#### Applicable Links or Attachments

![Screenshot](https://user-images.githubusercontent.com/50463727/162894081-e4bd35fa-a1d9-434e-875a-5bc94cd1e7c5.jpg)

#### Steps to Reproduce

1. Open top.gg
2. Edit any of your already approved bots
3. Scroll down to the optional info and you will see the "notes for reviewers" field

#### Web Browser and Version

Brave 1.37.112, Chromium 100. 0.4896.79

#### Operating System and Version

Android 11

#### Screen Resolution

1080 x 2340

**Comment by apenasigordev** [comment]
I didn't really see this in ``edit bot``
