### ISSUE TITLE
Add Privacy Policy section to the Add Bot Page!

### ISSUE THREAD

**Issue by DevMike123** [top-gg/issues#891]
#### Suggestion

I think that we should add a Privacy Policy section where Dev's will give link to their bot's privacy policy and submit the bot and reviewers will go through the policy and accordingly approve/deny the bot.

- Even Discord Dev Portal asks for it as it's required for users to know what data of them is stored or used by the bot.

- Make the Privacy Policy section a required field.

#### Contact

- DevMike123#5828

**Comment by Hopefuls** [comment]
Please use https://feedback.top.gg for feature suggestions.

**Comment by reisxd** [comment]
You should suggest this at https://feedback.top.gg

**Comment by DevMike123** [comment]
Thanks for telling!
