### ISSUE TITLE
Team management is fundamentally broken

### ISSUE THREAD

**Issue by FlitPix** [top-gg/issues#901]
#### Expected Behavior

I expected the team I've just created to be editable, and immediately visible on my user profile.

#### Observed Behavior

I cannot edit my team, and it is not visible on my user profile.

#### Applicable Links or Attachments

[My team](https://top.gg/team/415243580175765504)

#### Steps to Reproduce

1. Open Top.gg
2. Create a new team
3. Attempt to edit the team - you will observe that no changes are saved, and the Changes Saved notice doesn't appear
4. Attempt to view your user profile - you will observe that your team is not listed

#### Web Browser and Version

Firefox 109.0.1

#### Operating System and Version

Linux Mint 21.1

#### Screen Resolution

1920x1080

#### Additional information

I have also tested this in both Firefox 110.0.1 and Vivaldi 5.6.2868.36 on Android 13. The issue persisted.

The team does exist, as I am able to access it via direct link on multiple platforms, and I am able to add my server to it, but it cannot be edited and it is not publicly visible. I don't want to transfer ownership of my content to the team unless I know for sure that it won't cause problems.

**Comment by stranzero** [comment]
I believe I am having a similar issue to you.

**Comment by pixxies** [comment]
We don't check these issues anymore. Please contact our staff in our Discord server: https://top.gg/discord
