### ISSUE TITLE
Upvote not registering on phone

### ISSUE THREAD

**Issue by Y-O-YO** [top-gg/issues#902]
#### Expected Behavior

Follow upvote link from dank memer and vote 

#### Observed Behavior

Instead I found it shows the ad then allows me to vote but does not register on dank memer. 

#### Steps to Reproduce

1. Follow vote link from dank memer
2. Watch ad until vote button is available
3. Press the vote button
4. Return to dank memer and run /vote and it did not register that I voted

#### Web Browser and Version

Chrome 110.0.5481.153
Firefox 110.0.1

#### Operating System and Version

Android 13 Pixel 5

#### Screen Resolution

It might be because I visited a non existing page

#### Additional Information/Comments

Cleared cache and app storage on phone and in browsers. Reset PW in discord. 
Am able to upvote on PC.

**Comment by BerBerOnGithub** [comment]
confirmed that its the same problem on my pc
